dist: trusty
sudo: required
language:
  - cpp
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
env:
  global:
    - DESTDIR="${TRAVIS_BUILD_DIR}/destdir"
    - PKG_CONFIG_PATH="${DESTDIR}${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
    - LD_LIBRARY_PATH="${DESTDIR}${PREFIX}/lib:${LD_LIBRARY_PATH}"
    - CFLAGS="-I${DESTDIR}${PREFIX}/include"
    - CMOCKA_LIBS="-L${DESTDIR}${PREFIX}/lib -lcmocka"

script:
  # Link gcc-9 and g++-9 to their standard commands
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # install doxygen
  - sudo apt install doxygen -y
  # install cmocka
  # - sudo apt install libcmocka0 libcmocka-dev -y
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -Jxvf cmocka-1.0.1.tar.xz
  - mkdir cmocka-1.0.1/build && pushd cmocka-1.0.1/build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release
  - make -j$(nproc) install
  # install mbed tls
  - make install-mbedtls
  # build project in release mode
  - make build-ci
  # change to builddir and run tests
  - cd build && ctest
