dist: trusty
sudo: required
language:
  - cpp
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
env:
  global:
    - DESTDIR="${TRAVIS_BUILD_DIR}/destdir"
    - PREFIX=/usr
    - LD_LIBRARY_PATH="${DESTDIR}${PREFIX}/lib:${LD_LIBRARY_PATH}"
    # - CMOCKA_LIBS="-L${DESTDIR}${PREFIX}/lib -lcmocka"
   

script:
  # Link gcc-9 and g++-9 to their standard commands
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # install doxygen
  - sudo apt install doxygen -y
  # install cmocka
  - make install-cmocka
  # install mbed tls
  - make install-mbedtls
  # build project in release mode
  - make build-ci
  # change to builddir and run tests
  - cd build && ctest
