dist: xenial
sudo: required
language:
  - cpp
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - cmake
   
before_install:
  - sudo apt install doxygen graphviz -y
  - sudo apt install valgrind -y
  - make install-cmocka
  - make install-mbedtls

script:
  # Link gcc-9 and g++-9 to their standard commands
  - sudo ln -s /usr/bin/gcc-10 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-10 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-10
  - export CXX=/usr/bin/g++-10
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # build project in release mode
  - make build-ci
  # change to builddir and run tests
  - cd build && ctest --extra-verbose

before_deploy:
  - make run-valgrind

deploy: # this is a hacky workaround as script provider is causing problems
  skip_cleanup: true
  provider: releases
  script: .scripts/valgrind
  on:
    branch: master
    tags: true
    repo: RTradeLtd/libcp2p

notifications:
  email: false