dist: trusty
sudo: required
language:
  - cpp
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
   
before_install:
  - sudo apt install doxygen graphviz -y
  - sudo apt install valgrind -y
  - make install-cmocka
  - make install-mbedtls
  - make install-tinycbor

script:
  # Link gcc-9 and g++-9 to their standard commands
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # build project in release mode
  - make build-ci
  # change to builddir and run tests
  - cd build && ctest --extra-verbose

before_deploy:
  - make run-valgrind

deploy: # this is a hacky workaround as script provider is causing problems
  skip_cleanup: true
  provider: releases
  script: .scripts/valgrind
  on:
    branch: master
    tags: true
    repo: RTradeLtd/libcp2p

notifications:
  email: false
