.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/utils Directory Reference" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBvarhexutils\&.h\fP"
.br
.RI "provides utilities for manipulating hexadecimal data "
.ti -1c
.RI "file \fBvarint\&.h\fP"
.br
.RI "provides utilities for manipulating varints "
.in -1c
