.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multicodec Directory Reference" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multicodec Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcodecs\&.h\fP"
.br
.RI "macro definitions of all supported codecs "
.ti -1c
.RI "file \fBmulticodec\&.h\fP"
.br
.RI "an implemention of multicodec "
.in -1c
