.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/network Directory Reference" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/network Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBsocket\&.h\fP"
.br
.RI "general socket related tooling "
.ti -1c
.RI "file \fBsocket_client\&.h\fP"
.br
.RI "stuff related to socket clients (ie, connecting to socket servers) "
.ti -1c
.RI "file \fBsocket_server\&.h\fP"
.br
.RI "used to create a tcp/udp socket server listening on multiaddrs "
.in -1c
