.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/crypto Directory Reference" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/crypto Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaes\&.h\fP"
.br
.RI "proivides aes encryption/decryption functions "
.ti -1c
.RI "file \fBecdsa\&.h\fP"
.br
.RI "provides ECDSA cryptography support "
.ti -1c
.RI "file \fBephemeral\&.h\fP"
.br
.ti -1c
.RI "file \fBkey\&.h\fP"
.br
.ti -1c
.RI "file \fBpeerutils\&.h\fP"
.br
.RI "provides utilities for managing peer identifiers "
.ti -1c
.RI "file \fBsha1\&.h\fP"
.br
.RI "provides sha1 hashing support "
.ti -1c
.RI "file \fBsha256\&.h\fP"
.br
.RI "provides sha256 hashing support "
.ti -1c
.RI "file \fBsha512\&.h\fP"
.br
.RI "provides sha512 hashing support "
.ti -1c
.RI "file \fButil\&.h\fP"
.br
.RI "utility functions for working with crypto "
.in -1c
