.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/utils Directory Reference" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcolors\&.h\fP"
.br
.RI "macros and utilities for printing color to stdout from https://www.quora.com/How-do-I-print-a-colored-output-in-C Pass a \fCCOLORS_x\fP enum value into \fCprint_colored\fP and the color will be printed on stdout Note that if you want to disable printing of that color you'll have to send the \fCCOLORS_RESET\fP enum value through to make non-bold change 0->1 (0;31m red) vs (1;31m bold red) "
.ti -1c
.RI "file \fBlogger\&.h\fP"
.br
.RI "a thread safe logger with optional printf style logging "
.ti -1c
.RI "file \fBthread_pool\&.h\fP"
.br
.ti -1c
.RI "file \fBvarhexutils\&.h\fP"
.br
.RI "provides utilities for manipulating hexadecimal data "
.ti -1c
.RI "file \fBvarint\&.h\fP"
.br
.RI "provides utilities for manipulating varints "
.in -1c
