.TH "addrinfo" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addrinfo \- alias for \fCstruct addrinfo\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SH "Detailed Description"
.PP 
alias for \fCstruct addrinfo\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
