.TH "addrinfo" 3 "Tue Jul 21 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
addrinfo \- alias for \fCstruct addrinfo\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SH "Detailed Description"
.PP 
alias for \fCstruct addrinfo\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
