.TH "arg_end" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_end
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argtable3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBarg_hdr\fP \fBhdr\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int * \fBerror\fP"
.br
.ti -1c
.RI "void ** \fBparent\fP"
.br
.ti -1c
.RI "const char ** \fBargval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 162 of file argtable3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const char** arg_end::argval"

.PP
Definition at line 167 of file argtable3\&.h\&.
.SS "int arg_end::count"

.PP
Definition at line 164 of file argtable3\&.h\&.
.SS "int* arg_end::error"

.PP
Definition at line 165 of file argtable3\&.h\&.
.SS "struct \fBarg_hdr\fP arg_end::hdr"

.PP
Definition at line 163 of file argtable3\&.h\&.
.SS "void** arg_end::parent"

.PP
Definition at line 166 of file argtable3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
