.TH "arg_int" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_int
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argtable3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBarg_hdr\fP \fBhdr\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "int * \fBival\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 122 of file argtable3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int arg_int::count"

.PP
Definition at line 124 of file argtable3\&.h\&.
.SS "struct \fBarg_hdr\fP arg_int::hdr"

.PP
Definition at line 123 of file argtable3\&.h\&.
.SS "int* arg_int::ival"

.PP
Definition at line 125 of file argtable3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
