.TH "arg_cmd_info" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_cmd_info
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argtable3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [100]"
.br
.ti -1c
.RI "char \fBdescription\fP [256]"
.br
.ti -1c
.RI "\fBarg_cmdfn\fP * \fBproc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 170 of file argtable3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char arg_cmd_info::description[256]"

.PP
Definition at line 172 of file argtable3\&.h\&.
.SS "char arg_cmd_info::name[100]"

.PP
Definition at line 171 of file argtable3\&.h\&.
.SS "\fBarg_cmdfn\fP* arg_cmd_info::proc"

.PP
Definition at line 173 of file argtable3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
