.TH "arg_dbl" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_dbl
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argtable3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBarg_hdr\fP \fBhdr\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "double * \fBdval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file argtable3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int arg_dbl::count"

.PP
Definition at line 130 of file argtable3\&.h\&.
.SS "double* arg_dbl::dval"

.PP
Definition at line 131 of file argtable3\&.h\&.
.SS "struct \fBarg_hdr\fP arg_dbl::hdr"

.PP
Definition at line 129 of file argtable3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
