.TH "arg_rem" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_rem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argtable3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBarg_hdr\fP \fBhdr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 113 of file argtable3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBarg_hdr\fP arg_rem::hdr"

.PP
Definition at line 114 of file argtable3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
