.TH "arg_str" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arg_str
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <argtable3\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBarg_hdr\fP \fBhdr\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "const char ** \fBsval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 134 of file argtable3\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int arg_str::count"

.PP
Definition at line 136 of file argtable3\&.h\&.
.SS "struct \fBarg_hdr\fP arg_str::hdr"

.PP
Definition at line 135 of file argtable3\&.h\&.
.SS "const char** arg_str::sval"

.PP
Definition at line 137 of file argtable3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
