.TH "base32_decode_context" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base32_decode_context
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned int \fBi\fP"
.br
.ti -1c
.RI "char \fBbuf\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file base32\&.c\&.
.SH "Field Documentation"
.PP 
.SS "char base32_decode_context::buf[8]"

.PP
Definition at line 54 of file base32\&.c\&.
.SS "unsigned int base32_decode_context::i"

.PP
Definition at line 53 of file base32\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
