.TH "bsem" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bsem
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.ti -1c
.RI "int \fBv\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file thread_pool\&.c\&.
.SH "Field Documentation"
.PP 
.SS "pthread_cond_t bsem::cond"

.PP
Definition at line 50 of file thread_pool\&.c\&.
.SS "pthread_mutex_t bsem::mutex"

.PP
Definition at line 49 of file thread_pool\&.c\&.
.SS "int bsem::v"

.PP
Definition at line 51 of file thread_pool\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
