.TH "Buffer" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Buffer
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char ** \fBptr\fP"
.br
.ti -1c
.RI "size_t * \fBlen\fP"
.br
.ti -1c
.RI "size_t \fBalloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file open_memstream\&.c\&.
.SH "Field Documentation"
.PP 
.SS "size_t Buffer::alloc"

.PP
Definition at line 53 of file open_memstream\&.c\&.
.SS "size_t* Buffer::len"

.PP
Definition at line 52 of file open_memstream\&.c\&.
.SS "char** Buffer::ptr"

.PP
Definition at line 51 of file open_memstream\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
