.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/tinycbor/cborencoder_close_container_checked.c" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/tinycbor/cborencoder_close_container_checked.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tinycbor/cbor\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_BSD_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_DEFAULT_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB__STDC_LIMIT_MACROS\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCborError\fP \fBcbor_encoder_close_container_checked\fP (\fBCborEncoder\fP *encoder, const \fBCborEncoder\fP *containerEncoder)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_LIMIT_MACROS   1"

.PP
Definition at line 28 of file cborencoder_close_container_checked\&.c\&.
.SS "#define _BSD_SOURCE   1"

.PP
Definition at line 25 of file cborencoder_close_container_checked\&.c\&.
.SS "#define _DEFAULT_SOURCE   1"

.PP
Definition at line 26 of file cborencoder_close_container_checked\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
