.TH "CborParser" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CborParser
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cbor\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const uint8_t * \fBend\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 301 of file cbor\&.h\&.
.SH "Field Documentation"
.PP 
.SS "const uint8_t* CborParser::end"

.PP
Definition at line 302 of file cbor\&.h\&.
.SS "uint32_t CborParser::flags"

.PP
Definition at line 303 of file cbor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
