.TH "cbor_encoded_data" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cbor_encoded_data
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cbor\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.RI "the actual cbor encoded data "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file cbor\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint8_t* cbor_encoded_data::data"

.PP
Definition at line 18 of file cbor\&.h\&.
.SS "size_t cbor_encoded_data::len"

.PP
the actual cbor encoded data 
.PP
Definition at line 19 of file cbor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
