.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/tinycbor/cborparser_dup_string.c" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/tinycbor/cborparser_dup_string.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tinycbor/cbor\&.h'\fP
.br
\fC#include 'tinycbor/compilersupport_p\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_BSD_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB_DEFAULT_SOURCE\fP   1"
.br
.ti -1c
.RI "#define \fB__STDC_LIMIT_MACROS\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCborError\fP \fB_cbor_value_dup_string\fP (const \fBCborValue\fP *value, void **buffer, size_t *buflen, \fBCborValue\fP *next)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __STDC_LIMIT_MACROS   1"

.PP
Definition at line 32 of file cborparser_dup_string\&.c\&.
.SS "#define _BSD_SOURCE   1"

.PP
Definition at line 26 of file cborparser_dup_string\&.c\&.
.SS "#define _DEFAULT_SOURCE   1"

.PP
Definition at line 29 of file cborparser_dup_string\&.c\&.
.SH "Function Documentation"
.PP 
.SS "\fBCborError\fP _cbor_value_dup_string (const \fBCborValue\fP * value, void ** buffer, size_t * buflen, \fBCborValue\fP * next)"

.PP
Definition at line 101 of file cborparser_dup_string\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
