.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/tinycbor/cborerrorstrings.c" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/tinycbor/cborerrorstrings.c
.SH SYNOPSIS
.br
.PP
\fC#include 'tinycbor/cbor\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_\fP(msg)   msg"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBcbor_error_string\fP (\fBCborError\fP error)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define _(msg)   msg"

.PP
Definition at line 28 of file cborerrorstrings\&.c\&.
.SH "Function Documentation"
.PP 
.SS "const char* cbor_error_string (\fBCborError\fP error)"
Returns the error string corresponding to the CBOR error condition \fIerror\fP\&. 
.PP
Definition at line 85 of file cborerrorstrings\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
