.TH "Cid" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "int \fBcodec\fP"
.br
.ti -1c
.RI "unsigned char * \fBhash\fP"
.br
.ti -1c
.RI "size_t \fBhash_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file cid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int Cid::codec"

.PP
Definition at line 46 of file cid\&.h\&.
.SS "unsigned char* Cid::hash"

.PP
Definition at line 47 of file cid\&.h\&.
.SS "size_t Cid::hash_length"

.PP
Definition at line 48 of file cid\&.h\&.
.SS "int Cid::version"

.PP
Definition at line 45 of file cid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
