.TH "CidSet" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CidSet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cid\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBCid\fP * \fBcid\fP"
.br
.ti -1c
.RI "struct \fBCidSet\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file cid\&.h\&.
.SH "Field Documentation"
.PP 
.SS "struct \fBCid\fP* CidSet::cid"

.PP
Definition at line 47 of file cid\&.h\&.
.SS "struct \fBCidSet\fP* CidSet::next"

.PP
Definition at line 48 of file cid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
