.TH "client_conn" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
client_conn \- a structure containing a file descriptor and address information  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket_number\fP"
.br
.ti -1c
.RI "\fBsock_addr_storage\fP * \fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a structure containing a file descriptor and address information 


.PP
\fBTodo\fP
.RS 4

.IP "\(bu" 2
enable a queue/list of these 
.PP
.RE
.PP

.PP
Definition at line 87 of file socket_server\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBsock_addr_storage\fP* client_conn::address"

.PP
Definition at line 89 of file socket_server\&.h\&.
.SS "int client_conn::socket_number"

.PP
Definition at line 88 of file socket_server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
