.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multicodec/codecs.h" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multicodec/codecs.h \- macro definitions of all supported codecs  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIDENTITY\fP   '0x00'"
.br
.ti -1c
.RI "#define \fBIP4\fP   '0x04'"
.br
.ti -1c
.RI "#define \fBTCP\fP   '0x06'"
.br
.ti -1c
.RI "#define \fBSHA1\fP   '0x11'"
.br
.ti -1c
.RI "#define \fBSHA2_256\fP   '0x12'"
.br
.ti -1c
.RI "#define \fBSHA2_512\fP   '0x13'"
.br
.ti -1c
.RI "#define \fBSHA3_512\fP   '0x14'"
.br
.ti -1c
.RI "#define \fBSHA3_384\fP   '0x15'"
.br
.ti -1c
.RI "#define \fBSHA3_256\fP   '0x16'"
.br
.ti -1c
.RI "#define \fBSHA3_224\fP   '0x17'"
.br
.ti -1c
.RI "#define \fBSHAKE_128\fP   '0x18'"
.br
.ti -1c
.RI "#define \fBSHAKE_256\fP   '0x19'"
.br
.ti -1c
.RI "#define \fBKECCAK_224\fP   '0x1a'"
.br
.ti -1c
.RI "#define \fBKECCAK_256\fP   '0x1b'"
.br
.ti -1c
.RI "#define \fBKECCAK_384\fP   '0x1c'"
.br
.ti -1c
.RI "#define \fBKECCAK_512\fP   '0x1d'"
.br
.ti -1c
.RI "#define \fBBLAKE3\fP   '0x1e'"
.br
.ti -1c
.RI "#define \fBDCCP\fP   '0x21'"
.br
.ti -1c
.RI "#define \fBMURMUR3_128\fP   '0x22'"
.br
.ti -1c
.RI "#define \fBMURMUR3_32\fP   '0x23'"
.br
.ti -1c
.RI "#define \fBIP6\fP   '0x29'"
.br
.ti -1c
.RI "#define \fBIP6ZONE\fP   '0x2a'"
.br
.ti -1c
.RI "#define \fBPATH\fP   '0x2f'"
.br
.ti -1c
.RI "#define \fBMULTICODEC\fP   '0x30'"
.br
.ti -1c
.RI "#define \fBMULTIHASH\fP   '0x31'"
.br
.ti -1c
.RI "#define \fBMULTIADDR\fP   '0x32'"
.br
.ti -1c
.RI "#define \fBMULTIBASE\fP   '0x33'"
.br
.ti -1c
.RI "#define \fBDNS\fP   '0x35'"
.br
.ti -1c
.RI "#define \fBDNS4\fP   '0x36'"
.br
.ti -1c
.RI "#define \fBDNS6\fP   '0x37'"
.br
.ti -1c
.RI "#define \fBDNSADDR\fP   '0x38'"
.br
.ti -1c
.RI "#define \fBPROTOBUF\fP   '0x50'"
.br
.ti -1c
.RI "#define \fBCBOR\fP   '0x51'"
.br
.ti -1c
.RI "#define \fBRAW\fP   '0x55'"
.br
.ti -1c
.RI "#define \fBDBL_SHA2_256\fP   '0x56'"
.br
.ti -1c
.RI "#define \fBRLP\fP   '0x60'"
.br
.ti -1c
.RI "#define \fBBENCODE\fP   '0x63'"
.br
.ti -1c
.RI "#define \fBDAG_PB\fP   '0x70'"
.br
.ti -1c
.RI "#define \fBDAG_CBOR\fP   '0x71'"
.br
.ti -1c
.RI "#define \fBLIBP2P_KEY\fP   '0x72'"
.br
.ti -1c
.RI "#define \fBGIT_RAW\fP   '0x78'"
.br
.ti -1c
.RI "#define \fBTORRENT_INFO\fP   '0x7b'"
.br
.ti -1c
.RI "#define \fBTORRENT_FILE\fP   '0x7c'"
.br
.ti -1c
.RI "#define \fBLEOFCOIN_BLOCK\fP   '0x81'"
.br
.ti -1c
.RI "#define \fBLEOFCOIN_TX\fP   '0x82'"
.br
.ti -1c
.RI "#define \fBLEOFCOIN_PR\fP   '0x83'"
.br
.ti -1c
.RI "#define \fBSCTP\fP   '0x84'"
.br
.ti -1c
.RI "#define \fBDAG_JOSE\fP   '0x85'"
.br
.ti -1c
.RI "#define \fBDAG_COSE\fP   '0x86'"
.br
.ti -1c
.RI "#define \fBETH_BLOCK\fP   '0x90'"
.br
.ti -1c
.RI "#define \fBETH_BLOCK_LIST\fP   '0x91'"
.br
.ti -1c
.RI "#define \fBETH_TX_TRIE\fP   '0x92'"
.br
.ti -1c
.RI "#define \fBETH_TX\fP   '0x93'"
.br
.ti -1c
.RI "#define \fBETH_TX_RECEIPT_TRIE\fP   '0x94'"
.br
.ti -1c
.RI "#define \fBETH_TX_RECEIPT\fP   '0x95'"
.br
.ti -1c
.RI "#define \fBETH_STATE_TRIE\fP   '0x96'"
.br
.ti -1c
.RI "#define \fBETH_ACCOUNT_SNAPSHOT\fP   '0x97'"
.br
.ti -1c
.RI "#define \fBETH_STORAGE_TRIE\fP   '0x98'"
.br
.ti -1c
.RI "#define \fBBITCOIN_BLOCK\fP   '0xb0'"
.br
.ti -1c
.RI "#define \fBBITCOIN_TX\fP   '0xb1'"
.br
.ti -1c
.RI "#define \fBBITCOIN_WITNESS_COMMITMENT\fP   '0xb2'"
.br
.ti -1c
.RI "#define \fBZCASH_BLOCK\fP   '0xc0'"
.br
.ti -1c
.RI "#define \fBZCASH_TX\fP   '0xc1'"
.br
.ti -1c
.RI "#define \fBSTELLAR_BLOCK\fP   '0xd0'"
.br
.ti -1c
.RI "#define \fBSTELLAR_TX\fP   '0xd1'"
.br
.ti -1c
.RI "#define \fBMD4\fP   '0xd4'"
.br
.ti -1c
.RI "#define \fBMD5\fP   '0xd5'"
.br
.ti -1c
.RI "#define \fBBMT\fP   '0xd6'"
.br
.ti -1c
.RI "#define \fBDECRED_BLOCK\fP   '0xe0'"
.br
.ti -1c
.RI "#define \fBDECRED_TX\fP   '0xe1'"
.br
.ti -1c
.RI "#define \fBIPLD_NS\fP   '0xe2'"
.br
.ti -1c
.RI "#define \fBIPFS_NS\fP   '0xe3'"
.br
.ti -1c
.RI "#define \fBSWARM_NS\fP   '0xe4'"
.br
.ti -1c
.RI "#define \fBIPNS_NS\fP   '0xe5'"
.br
.ti -1c
.RI "#define \fBZERONET\fP   '0xe6'"
.br
.ti -1c
.RI "#define \fBSECP256K1_PUB\fP   '0xe7'"
.br
.ti -1c
.RI "#define \fBBLS12_381_G1_PUB\fP   '0xea'"
.br
.ti -1c
.RI "#define \fBBLS12_381_G2_PUB\fP   '0xeb'"
.br
.ti -1c
.RI "#define \fBX25519_PUB\fP   '0xec'"
.br
.ti -1c
.RI "#define \fBED25519_PUB\fP   '0xed'"
.br
.ti -1c
.RI "#define \fBDASH_BLOCK\fP   '0xf0'"
.br
.ti -1c
.RI "#define \fBDASH_TX\fP   '0xf1'"
.br
.ti -1c
.RI "#define \fBSWARM_MANIFEST\fP   '0xfa'"
.br
.ti -1c
.RI "#define \fBSWARM_FEED\fP   '0xfb'"
.br
.ti -1c
.RI "#define \fBUDP\fP   '0x0111'"
.br
.ti -1c
.RI "#define \fBP2P_WEBRTC_STAR\fP   '0x0113'"
.br
.ti -1c
.RI "#define \fBP2P_WEBRTC_DIRECT\fP   '0x0114'"
.br
.ti -1c
.RI "#define \fBP2P_STARDUST\fP   '0x0115'"
.br
.ti -1c
.RI "#define \fBP2P_CIRCUIT\fP   '0x0122'"
.br
.ti -1c
.RI "#define \fBDAG_JSON\fP   '0x0129'"
.br
.ti -1c
.RI "#define \fBUDT\fP   '0x012d'"
.br
.ti -1c
.RI "#define \fBUTP\fP   '0x012e'"
.br
.ti -1c
.RI "#define \fBUNIX\fP   '0x0190'"
.br
.ti -1c
.RI "#define \fBP2P\fP   '0x01a5'"
.br
.ti -1c
.RI "#define \fBIPFS\fP   '0x01a5'"
.br
.ti -1c
.RI "#define \fBHTTPS\fP   '0x01bb'"
.br
.ti -1c
.RI "#define \fBONION\fP   '0x01bc'"
.br
.ti -1c
.RI "#define \fBONION3\fP   '0x01bd'"
.br
.ti -1c
.RI "#define \fBGARLIC64\fP   '0x01be'"
.br
.ti -1c
.RI "#define \fBGARLIC32\fP   '0x01bf'"
.br
.ti -1c
.RI "#define \fBTLS\fP   '0x01c0'"
.br
.ti -1c
.RI "#define \fBQUIC\fP   '0x01cc'"
.br
.ti -1c
.RI "#define \fBWS\fP   '0x01dd'"
.br
.ti -1c
.RI "#define \fBWSS\fP   '0x01de'"
.br
.ti -1c
.RI "#define \fBP2P_WEBSOCKET_STAR\fP   '0x01df'"
.br
.ti -1c
.RI "#define \fBHTTP\fP   '0x01e0'"
.br
.ti -1c
.RI "#define \fBJSON\fP   '0x0200'"
.br
.ti -1c
.RI "#define \fBMESSAGEPACK\fP   '0x0201'"
.br
.ti -1c
.RI "#define \fBLIBP2P_PEER_RECORD\fP   '0x0301'"
.br
.ti -1c
.RI "#define \fBSHA2_256_TRUNC254_PADDED\fP   '0x1012'"
.br
.ti -1c
.RI "#define \fBRIPEMD_128\fP   '0x1052'"
.br
.ti -1c
.RI "#define \fBRIPEMD_160\fP   '0x1053'"
.br
.ti -1c
.RI "#define \fBRIPEMD_256\fP   '0x1054'"
.br
.ti -1c
.RI "#define \fBRIPEMD_320\fP   '0x1055'"
.br
.ti -1c
.RI "#define \fBX11\fP   '0x1100'"
.br
.ti -1c
.RI "#define \fBSM3_256\fP   '0x534d'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_8\fP   '0xb201'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_16\fP   '0xb202'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_24\fP   '0xb203'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_32\fP   '0xb204'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_40\fP   '0xb205'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_48\fP   '0xb206'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_56\fP   '0xb207'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_64\fP   '0xb208'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_72\fP   '0xb209'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_80\fP   '0xb20a'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_88\fP   '0xb20b'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_96\fP   '0xb20c'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_104\fP   '0xb20d'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_112\fP   '0xb20e'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_120\fP   '0xb20f'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_128\fP   '0xb210'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_136\fP   '0xb211'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_144\fP   '0xb212'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_152\fP   '0xb213'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_160\fP   '0xb214'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_168\fP   '0xb215'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_176\fP   '0xb216'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_184\fP   '0xb217'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_192\fP   '0xb218'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_200\fP   '0xb219'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_208\fP   '0xb21a'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_216\fP   '0xb21b'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_224\fP   '0xb21c'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_232\fP   '0xb21d'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_240\fP   '0xb21e'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_248\fP   '0xb21f'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_256\fP   '0xb220'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_264\fP   '0xb221'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_272\fP   '0xb222'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_280\fP   '0xb223'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_288\fP   '0xb224'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_296\fP   '0xb225'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_304\fP   '0xb226'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_312\fP   '0xb227'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_320\fP   '0xb228'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_328\fP   '0xb229'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_336\fP   '0xb22a'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_344\fP   '0xb22b'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_352\fP   '0xb22c'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_360\fP   '0xb22d'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_368\fP   '0xb22e'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_376\fP   '0xb22f'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_384\fP   '0xb230'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_392\fP   '0xb231'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_400\fP   '0xb232'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_408\fP   '0xb233'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_416\fP   '0xb234'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_424\fP   '0xb235'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_432\fP   '0xb236'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_440\fP   '0xb237'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_448\fP   '0xb238'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_456\fP   '0xb239'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_464\fP   '0xb23a'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_472\fP   '0xb23b'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_480\fP   '0xb23c'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_488\fP   '0xb23d'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_496\fP   '0xb23e'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_504\fP   '0xb23f'"
.br
.ti -1c
.RI "#define \fBBLAKE2B_512\fP   '0xb240'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_8\fP   '0xb241'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_16\fP   '0xb242'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_24\fP   '0xb243'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_32\fP   '0xb244'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_40\fP   '0xb245'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_48\fP   '0xb246'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_56\fP   '0xb247'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_64\fP   '0xb248'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_72\fP   '0xb249'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_80\fP   '0xb24a'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_88\fP   '0xb24b'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_96\fP   '0xb24c'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_104\fP   '0xb24d'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_112\fP   '0xb24e'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_120\fP   '0xb24f'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_128\fP   '0xb250'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_136\fP   '0xb251'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_144\fP   '0xb252'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_152\fP   '0xb253'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_160\fP   '0xb254'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_168\fP   '0xb255'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_176\fP   '0xb256'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_184\fP   '0xb257'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_192\fP   '0xb258'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_200\fP   '0xb259'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_208\fP   '0xb25a'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_216\fP   '0xb25b'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_224\fP   '0xb25c'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_232\fP   '0xb25d'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_240\fP   '0xb25e'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_248\fP   '0xb25f'"
.br
.ti -1c
.RI "#define \fBBLAKE2S_256\fP   '0xb260'"
.br
.ti -1c
.RI "#define \fBSKEIN256_8\fP   '0xb301'"
.br
.ti -1c
.RI "#define \fBSKEIN256_16\fP   '0xb302'"
.br
.ti -1c
.RI "#define \fBSKEIN256_24\fP   '0xb303'"
.br
.ti -1c
.RI "#define \fBSKEIN256_32\fP   '0xb304'"
.br
.ti -1c
.RI "#define \fBSKEIN256_40\fP   '0xb305'"
.br
.ti -1c
.RI "#define \fBSKEIN256_48\fP   '0xb306'"
.br
.ti -1c
.RI "#define \fBSKEIN256_56\fP   '0xb307'"
.br
.ti -1c
.RI "#define \fBSKEIN256_64\fP   '0xb308'"
.br
.ti -1c
.RI "#define \fBSKEIN256_72\fP   '0xb309'"
.br
.ti -1c
.RI "#define \fBSKEIN256_80\fP   '0xb30a'"
.br
.ti -1c
.RI "#define \fBSKEIN256_88\fP   '0xb30b'"
.br
.ti -1c
.RI "#define \fBSKEIN256_96\fP   '0xb30c'"
.br
.ti -1c
.RI "#define \fBSKEIN256_104\fP   '0xb30d'"
.br
.ti -1c
.RI "#define \fBSKEIN256_112\fP   '0xb30e'"
.br
.ti -1c
.RI "#define \fBSKEIN256_120\fP   '0xb30f'"
.br
.ti -1c
.RI "#define \fBSKEIN256_128\fP   '0xb310'"
.br
.ti -1c
.RI "#define \fBSKEIN256_136\fP   '0xb311'"
.br
.ti -1c
.RI "#define \fBSKEIN256_144\fP   '0xb312'"
.br
.ti -1c
.RI "#define \fBSKEIN256_152\fP   '0xb313'"
.br
.ti -1c
.RI "#define \fBSKEIN256_160\fP   '0xb314'"
.br
.ti -1c
.RI "#define \fBSKEIN256_168\fP   '0xb315'"
.br
.ti -1c
.RI "#define \fBSKEIN256_176\fP   '0xb316'"
.br
.ti -1c
.RI "#define \fBSKEIN256_184\fP   '0xb317'"
.br
.ti -1c
.RI "#define \fBSKEIN256_192\fP   '0xb318'"
.br
.ti -1c
.RI "#define \fBSKEIN256_200\fP   '0xb319'"
.br
.ti -1c
.RI "#define \fBSKEIN256_208\fP   '0xb31a'"
.br
.ti -1c
.RI "#define \fBSKEIN256_216\fP   '0xb31b'"
.br
.ti -1c
.RI "#define \fBSKEIN256_224\fP   '0xb31c'"
.br
.ti -1c
.RI "#define \fBSKEIN256_232\fP   '0xb31d'"
.br
.ti -1c
.RI "#define \fBSKEIN256_240\fP   '0xb31e'"
.br
.ti -1c
.RI "#define \fBSKEIN256_248\fP   '0xb31f'"
.br
.ti -1c
.RI "#define \fBSKEIN256_256\fP   '0xb320'"
.br
.ti -1c
.RI "#define \fBSKEIN512_8\fP   '0xb321'"
.br
.ti -1c
.RI "#define \fBSKEIN512_16\fP   '0xb322'"
.br
.ti -1c
.RI "#define \fBSKEIN512_24\fP   '0xb323'"
.br
.ti -1c
.RI "#define \fBSKEIN512_32\fP   '0xb324'"
.br
.ti -1c
.RI "#define \fBSKEIN512_40\fP   '0xb325'"
.br
.ti -1c
.RI "#define \fBSKEIN512_48\fP   '0xb326'"
.br
.ti -1c
.RI "#define \fBSKEIN512_56\fP   '0xb327'"
.br
.ti -1c
.RI "#define \fBSKEIN512_64\fP   '0xb328'"
.br
.ti -1c
.RI "#define \fBSKEIN512_72\fP   '0xb329'"
.br
.ti -1c
.RI "#define \fBSKEIN512_80\fP   '0xb32a'"
.br
.ti -1c
.RI "#define \fBSKEIN512_88\fP   '0xb32b'"
.br
.ti -1c
.RI "#define \fBSKEIN512_96\fP   '0xb32c'"
.br
.ti -1c
.RI "#define \fBSKEIN512_104\fP   '0xb32d'"
.br
.ti -1c
.RI "#define \fBSKEIN512_112\fP   '0xb32e'"
.br
.ti -1c
.RI "#define \fBSKEIN512_120\fP   '0xb32f'"
.br
.ti -1c
.RI "#define \fBSKEIN512_128\fP   '0xb330'"
.br
.ti -1c
.RI "#define \fBSKEIN512_136\fP   '0xb331'"
.br
.ti -1c
.RI "#define \fBSKEIN512_144\fP   '0xb332'"
.br
.ti -1c
.RI "#define \fBSKEIN512_152\fP   '0xb333'"
.br
.ti -1c
.RI "#define \fBSKEIN512_160\fP   '0xb334'"
.br
.ti -1c
.RI "#define \fBSKEIN512_168\fP   '0xb335'"
.br
.ti -1c
.RI "#define \fBSKEIN512_176\fP   '0xb336'"
.br
.ti -1c
.RI "#define \fBSKEIN512_184\fP   '0xb337'"
.br
.ti -1c
.RI "#define \fBSKEIN512_192\fP   '0xb338'"
.br
.ti -1c
.RI "#define \fBSKEIN512_200\fP   '0xb339'"
.br
.ti -1c
.RI "#define \fBSKEIN512_208\fP   '0xb33a'"
.br
.ti -1c
.RI "#define \fBSKEIN512_216\fP   '0xb33b'"
.br
.ti -1c
.RI "#define \fBSKEIN512_224\fP   '0xb33c'"
.br
.ti -1c
.RI "#define \fBSKEIN512_232\fP   '0xb33d'"
.br
.ti -1c
.RI "#define \fBSKEIN512_240\fP   '0xb33e'"
.br
.ti -1c
.RI "#define \fBSKEIN512_248\fP   '0xb33f'"
.br
.ti -1c
.RI "#define \fBSKEIN512_256\fP   '0xb340'"
.br
.ti -1c
.RI "#define \fBSKEIN512_264\fP   '0xb341'"
.br
.ti -1c
.RI "#define \fBSKEIN512_272\fP   '0xb342'"
.br
.ti -1c
.RI "#define \fBSKEIN512_280\fP   '0xb343'"
.br
.ti -1c
.RI "#define \fBSKEIN512_288\fP   '0xb344'"
.br
.ti -1c
.RI "#define \fBSKEIN512_296\fP   '0xb345'"
.br
.ti -1c
.RI "#define \fBSKEIN512_304\fP   '0xb346'"
.br
.ti -1c
.RI "#define \fBSKEIN512_312\fP   '0xb347'"
.br
.ti -1c
.RI "#define \fBSKEIN512_320\fP   '0xb348'"
.br
.ti -1c
.RI "#define \fBSKEIN512_328\fP   '0xb349'"
.br
.ti -1c
.RI "#define \fBSKEIN512_336\fP   '0xb34a'"
.br
.ti -1c
.RI "#define \fBSKEIN512_344\fP   '0xb34b'"
.br
.ti -1c
.RI "#define \fBSKEIN512_352\fP   '0xb34c'"
.br
.ti -1c
.RI "#define \fBSKEIN512_360\fP   '0xb34d'"
.br
.ti -1c
.RI "#define \fBSKEIN512_368\fP   '0xb34e'"
.br
.ti -1c
.RI "#define \fBSKEIN512_376\fP   '0xb34f'"
.br
.ti -1c
.RI "#define \fBSKEIN512_384\fP   '0xb350'"
.br
.ti -1c
.RI "#define \fBSKEIN512_392\fP   '0xb351'"
.br
.ti -1c
.RI "#define \fBSKEIN512_400\fP   '0xb352'"
.br
.ti -1c
.RI "#define \fBSKEIN512_408\fP   '0xb353'"
.br
.ti -1c
.RI "#define \fBSKEIN512_416\fP   '0xb354'"
.br
.ti -1c
.RI "#define \fBSKEIN512_424\fP   '0xb355'"
.br
.ti -1c
.RI "#define \fBSKEIN512_432\fP   '0xb356'"
.br
.ti -1c
.RI "#define \fBSKEIN512_440\fP   '0xb357'"
.br
.ti -1c
.RI "#define \fBSKEIN512_448\fP   '0xb358'"
.br
.ti -1c
.RI "#define \fBSKEIN512_456\fP   '0xb359'"
.br
.ti -1c
.RI "#define \fBSKEIN512_464\fP   '0xb35a'"
.br
.ti -1c
.RI "#define \fBSKEIN512_472\fP   '0xb35b'"
.br
.ti -1c
.RI "#define \fBSKEIN512_480\fP   '0xb35c'"
.br
.ti -1c
.RI "#define \fBSKEIN512_488\fP   '0xb35d'"
.br
.ti -1c
.RI "#define \fBSKEIN512_496\fP   '0xb35e'"
.br
.ti -1c
.RI "#define \fBSKEIN512_504\fP   '0xb35f'"
.br
.ti -1c
.RI "#define \fBSKEIN512_512\fP   '0xb360'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_8\fP   '0xb361'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_16\fP   '0xb362'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_24\fP   '0xb363'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_32\fP   '0xb364'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_40\fP   '0xb365'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_48\fP   '0xb366'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_56\fP   '0xb367'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_64\fP   '0xb368'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_72\fP   '0xb369'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_80\fP   '0xb36a'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_88\fP   '0xb36b'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_96\fP   '0xb36c'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_104\fP   '0xb36d'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_112\fP   '0xb36e'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_120\fP   '0xb36f'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_128\fP   '0xb370'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_136\fP   '0xb371'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_144\fP   '0xb372'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_152\fP   '0xb373'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_160\fP   '0xb374'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_168\fP   '0xb375'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_176\fP   '0xb376'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_184\fP   '0xb377'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_192\fP   '0xb378'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_200\fP   '0xb379'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_208\fP   '0xb37a'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_216\fP   '0xb37b'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_224\fP   '0xb37c'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_232\fP   '0xb37d'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_240\fP   '0xb37e'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_248\fP   '0xb37f'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_256\fP   '0xb380'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_264\fP   '0xb381'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_272\fP   '0xb382'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_280\fP   '0xb383'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_288\fP   '0xb384'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_296\fP   '0xb385'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_304\fP   '0xb386'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_312\fP   '0xb387'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_320\fP   '0xb388'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_328\fP   '0xb389'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_336\fP   '0xb38a'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_344\fP   '0xb38b'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_352\fP   '0xb38c'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_360\fP   '0xb38d'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_368\fP   '0xb38e'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_376\fP   '0xb38f'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_384\fP   '0xb390'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_392\fP   '0xb391'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_400\fP   '0xb392'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_408\fP   '0xb393'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_416\fP   '0xb394'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_424\fP   '0xb395'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_432\fP   '0xb396'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_440\fP   '0xb397'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_448\fP   '0xb398'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_456\fP   '0xb399'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_464\fP   '0xb39a'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_472\fP   '0xb39b'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_480\fP   '0xb39c'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_488\fP   '0xb39d'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_496\fP   '0xb39e'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_504\fP   '0xb39f'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_512\fP   '0xb3a0'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_520\fP   '0xb3a1'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_528\fP   '0xb3a2'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_536\fP   '0xb3a3'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_544\fP   '0xb3a4'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_552\fP   '0xb3a5'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_560\fP   '0xb3a6'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_568\fP   '0xb3a7'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_576\fP   '0xb3a8'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_584\fP   '0xb3a9'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_592\fP   '0xb3aa'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_600\fP   '0xb3ab'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_608\fP   '0xb3ac'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_616\fP   '0xb3ad'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_624\fP   '0xb3ae'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_632\fP   '0xb3af'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_640\fP   '0xb3b0'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_648\fP   '0xb3b1'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_656\fP   '0xb3b2'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_664\fP   '0xb3b3'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_672\fP   '0xb3b4'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_680\fP   '0xb3b5'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_688\fP   '0xb3b6'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_696\fP   '0xb3b7'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_704\fP   '0xb3b8'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_712\fP   '0xb3b9'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_720\fP   '0xb3ba'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_728\fP   '0xb3bb'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_736\fP   '0xb3bc'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_744\fP   '0xb3bd'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_752\fP   '0xb3be'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_760\fP   '0xb3bf'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_768\fP   '0xb3c0'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_776\fP   '0xb3c1'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_784\fP   '0xb3c2'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_792\fP   '0xb3c3'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_800\fP   '0xb3c4'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_808\fP   '0xb3c5'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_816\fP   '0xb3c6'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_824\fP   '0xb3c7'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_832\fP   '0xb3c8'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_840\fP   '0xb3c9'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_848\fP   '0xb3ca'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_856\fP   '0xb3cb'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_864\fP   '0xb3cc'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_872\fP   '0xb3cd'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_880\fP   '0xb3ce'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_888\fP   '0xb3cf'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_896\fP   '0xb3d0'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_904\fP   '0xb3d1'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_912\fP   '0xb3d2'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_920\fP   '0xb3d3'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_928\fP   '0xb3d4'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_936\fP   '0xb3d5'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_944\fP   '0xb3d6'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_952\fP   '0xb3d7'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_960\fP   '0xb3d8'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_968\fP   '0xb3d9'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_976\fP   '0xb3da'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_984\fP   '0xb3db'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_992\fP   '0xb3dc'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_1000\fP   '0xb3dd'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_1008\fP   '0xb3de'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_1016\fP   '0xb3df'"
.br
.ti -1c
.RI "#define \fBSKEIN1024_1024\fP   '0xb3e0'"
.br
.ti -1c
.RI "#define \fBPOSEIDON_BLS12_381_A2_FC1\fP   '0xb401'"
.br
.ti -1c
.RI "#define \fBPOSEIDON_BLS12_381_A2_FC1_SC\fP   '0xb402'"
.br
.ti -1c
.RI "#define \fBFIL_COMMITMENT_UNSEALED\fP   '0xf101'"
.br
.ti -1c
.RI "#define \fBFIL_COMMITMENT_SEALED\fP   '0xf102'"
.br
.ti -1c
.RI "#define \fBHOLOCHAIN_ADR_V0\fP   '0x807124'"
.br
.ti -1c
.RI "#define \fBHOLOCHAIN_ADR_V1\fP   '0x817124'"
.br
.ti -1c
.RI "#define \fBHOLOCHAIN_KEY_V0\fP   '0x947124'"
.br
.ti -1c
.RI "#define \fBHOLOCHAIN_KEY_V1\fP   '0x957124'"
.br
.ti -1c
.RI "#define \fBHOLOCHAIN_SIG_V0\fP   '0xa27124'"
.br
.ti -1c
.RI "#define \fBHOLOCHAIN_SIG_V1\fP   '0xa37124'"
.br
.ti -1c
.RI "#define \fBCODECS_COUNT\fP   446"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBCODECS_LIST\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
macro definitions of all supported codecs 


.PP
\fBAuthor\fP
.RS 4
Bonedaddy
.RE
.PP
for actual multicodec functions see \fBmulticodec\&.h\fP 
.PP
\fBNote\fP
.RS 4
the 0xCert-imprint-256 codec is not supported as it is an invalid variable name 
.RE
.PP

.PP
Definition in file \fBcodecs\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define BENCODE   '0x63'"

.PP
Definition at line 59 of file codecs\&.h\&.
.SS "#define BITCOIN_BLOCK   '0xb0'"

.PP
Definition at line 81 of file codecs\&.h\&.
.SS "#define BITCOIN_TX   '0xb1'"

.PP
Definition at line 82 of file codecs\&.h\&.
.SS "#define BITCOIN_WITNESS_COMMITMENT   '0xb2'"

.PP
Definition at line 83 of file codecs\&.h\&.
.SS "#define BLAKE2B_104   '0xb20d'"

.PP
Definition at line 151 of file codecs\&.h\&.
.SS "#define BLAKE2B_112   '0xb20e'"

.PP
Definition at line 152 of file codecs\&.h\&.
.SS "#define BLAKE2B_120   '0xb20f'"

.PP
Definition at line 153 of file codecs\&.h\&.
.SS "#define BLAKE2B_128   '0xb210'"

.PP
Definition at line 154 of file codecs\&.h\&.
.SS "#define BLAKE2B_136   '0xb211'"

.PP
Definition at line 155 of file codecs\&.h\&.
.SS "#define BLAKE2B_144   '0xb212'"

.PP
Definition at line 156 of file codecs\&.h\&.
.SS "#define BLAKE2B_152   '0xb213'"

.PP
Definition at line 157 of file codecs\&.h\&.
.SS "#define BLAKE2B_16   '0xb202'"

.PP
Definition at line 140 of file codecs\&.h\&.
.SS "#define BLAKE2B_160   '0xb214'"

.PP
Definition at line 158 of file codecs\&.h\&.
.SS "#define BLAKE2B_168   '0xb215'"

.PP
Definition at line 159 of file codecs\&.h\&.
.SS "#define BLAKE2B_176   '0xb216'"

.PP
Definition at line 160 of file codecs\&.h\&.
.SS "#define BLAKE2B_184   '0xb217'"

.PP
Definition at line 161 of file codecs\&.h\&.
.SS "#define BLAKE2B_192   '0xb218'"

.PP
Definition at line 162 of file codecs\&.h\&.
.SS "#define BLAKE2B_200   '0xb219'"

.PP
Definition at line 163 of file codecs\&.h\&.
.SS "#define BLAKE2B_208   '0xb21a'"

.PP
Definition at line 164 of file codecs\&.h\&.
.SS "#define BLAKE2B_216   '0xb21b'"

.PP
Definition at line 165 of file codecs\&.h\&.
.SS "#define BLAKE2B_224   '0xb21c'"

.PP
Definition at line 166 of file codecs\&.h\&.
.SS "#define BLAKE2B_232   '0xb21d'"

.PP
Definition at line 167 of file codecs\&.h\&.
.SS "#define BLAKE2B_24   '0xb203'"

.PP
Definition at line 141 of file codecs\&.h\&.
.SS "#define BLAKE2B_240   '0xb21e'"

.PP
Definition at line 168 of file codecs\&.h\&.
.SS "#define BLAKE2B_248   '0xb21f'"

.PP
Definition at line 169 of file codecs\&.h\&.
.SS "#define BLAKE2B_256   '0xb220'"

.PP
Definition at line 170 of file codecs\&.h\&.
.SS "#define BLAKE2B_264   '0xb221'"

.PP
Definition at line 171 of file codecs\&.h\&.
.SS "#define BLAKE2B_272   '0xb222'"

.PP
Definition at line 172 of file codecs\&.h\&.
.SS "#define BLAKE2B_280   '0xb223'"

.PP
Definition at line 173 of file codecs\&.h\&.
.SS "#define BLAKE2B_288   '0xb224'"

.PP
Definition at line 174 of file codecs\&.h\&.
.SS "#define BLAKE2B_296   '0xb225'"

.PP
Definition at line 175 of file codecs\&.h\&.
.SS "#define BLAKE2B_304   '0xb226'"

.PP
Definition at line 176 of file codecs\&.h\&.
.SS "#define BLAKE2B_312   '0xb227'"

.PP
Definition at line 177 of file codecs\&.h\&.
.SS "#define BLAKE2B_32   '0xb204'"

.PP
Definition at line 142 of file codecs\&.h\&.
.SS "#define BLAKE2B_320   '0xb228'"

.PP
Definition at line 178 of file codecs\&.h\&.
.SS "#define BLAKE2B_328   '0xb229'"

.PP
Definition at line 179 of file codecs\&.h\&.
.SS "#define BLAKE2B_336   '0xb22a'"

.PP
Definition at line 180 of file codecs\&.h\&.
.SS "#define BLAKE2B_344   '0xb22b'"

.PP
Definition at line 181 of file codecs\&.h\&.
.SS "#define BLAKE2B_352   '0xb22c'"

.PP
Definition at line 182 of file codecs\&.h\&.
.SS "#define BLAKE2B_360   '0xb22d'"

.PP
Definition at line 183 of file codecs\&.h\&.
.SS "#define BLAKE2B_368   '0xb22e'"

.PP
Definition at line 184 of file codecs\&.h\&.
.SS "#define BLAKE2B_376   '0xb22f'"

.PP
Definition at line 185 of file codecs\&.h\&.
.SS "#define BLAKE2B_384   '0xb230'"

.PP
Definition at line 186 of file codecs\&.h\&.
.SS "#define BLAKE2B_392   '0xb231'"

.PP
Definition at line 187 of file codecs\&.h\&.
.SS "#define BLAKE2B_40   '0xb205'"

.PP
Definition at line 143 of file codecs\&.h\&.
.SS "#define BLAKE2B_400   '0xb232'"

.PP
Definition at line 188 of file codecs\&.h\&.
.SS "#define BLAKE2B_408   '0xb233'"

.PP
Definition at line 189 of file codecs\&.h\&.
.SS "#define BLAKE2B_416   '0xb234'"

.PP
Definition at line 190 of file codecs\&.h\&.
.SS "#define BLAKE2B_424   '0xb235'"

.PP
Definition at line 191 of file codecs\&.h\&.
.SS "#define BLAKE2B_432   '0xb236'"

.PP
Definition at line 192 of file codecs\&.h\&.
.SS "#define BLAKE2B_440   '0xb237'"

.PP
Definition at line 193 of file codecs\&.h\&.
.SS "#define BLAKE2B_448   '0xb238'"

.PP
Definition at line 194 of file codecs\&.h\&.
.SS "#define BLAKE2B_456   '0xb239'"

.PP
Definition at line 195 of file codecs\&.h\&.
.SS "#define BLAKE2B_464   '0xb23a'"

.PP
Definition at line 196 of file codecs\&.h\&.
.SS "#define BLAKE2B_472   '0xb23b'"

.PP
Definition at line 197 of file codecs\&.h\&.
.SS "#define BLAKE2B_48   '0xb206'"

.PP
Definition at line 144 of file codecs\&.h\&.
.SS "#define BLAKE2B_480   '0xb23c'"

.PP
Definition at line 198 of file codecs\&.h\&.
.SS "#define BLAKE2B_488   '0xb23d'"

.PP
Definition at line 199 of file codecs\&.h\&.
.SS "#define BLAKE2B_496   '0xb23e'"

.PP
Definition at line 200 of file codecs\&.h\&.
.SS "#define BLAKE2B_504   '0xb23f'"

.PP
Definition at line 201 of file codecs\&.h\&.
.SS "#define BLAKE2B_512   '0xb240'"

.PP
Definition at line 202 of file codecs\&.h\&.
.SS "#define BLAKE2B_56   '0xb207'"

.PP
Definition at line 145 of file codecs\&.h\&.
.SS "#define BLAKE2B_64   '0xb208'"

.PP
Definition at line 146 of file codecs\&.h\&.
.SS "#define BLAKE2B_72   '0xb209'"

.PP
Definition at line 147 of file codecs\&.h\&.
.SS "#define BLAKE2B_8   '0xb201'"

.PP
Definition at line 139 of file codecs\&.h\&.
.SS "#define BLAKE2B_80   '0xb20a'"

.PP
Definition at line 148 of file codecs\&.h\&.
.SS "#define BLAKE2B_88   '0xb20b'"

.PP
Definition at line 149 of file codecs\&.h\&.
.SS "#define BLAKE2B_96   '0xb20c'"

.PP
Definition at line 150 of file codecs\&.h\&.
.SS "#define BLAKE2S_104   '0xb24d'"

.PP
Definition at line 215 of file codecs\&.h\&.
.SS "#define BLAKE2S_112   '0xb24e'"

.PP
Definition at line 216 of file codecs\&.h\&.
.SS "#define BLAKE2S_120   '0xb24f'"

.PP
Definition at line 217 of file codecs\&.h\&.
.SS "#define BLAKE2S_128   '0xb250'"

.PP
Definition at line 218 of file codecs\&.h\&.
.SS "#define BLAKE2S_136   '0xb251'"

.PP
Definition at line 219 of file codecs\&.h\&.
.SS "#define BLAKE2S_144   '0xb252'"

.PP
Definition at line 220 of file codecs\&.h\&.
.SS "#define BLAKE2S_152   '0xb253'"

.PP
Definition at line 221 of file codecs\&.h\&.
.SS "#define BLAKE2S_16   '0xb242'"

.PP
Definition at line 204 of file codecs\&.h\&.
.SS "#define BLAKE2S_160   '0xb254'"

.PP
Definition at line 222 of file codecs\&.h\&.
.SS "#define BLAKE2S_168   '0xb255'"

.PP
Definition at line 223 of file codecs\&.h\&.
.SS "#define BLAKE2S_176   '0xb256'"

.PP
Definition at line 224 of file codecs\&.h\&.
.SS "#define BLAKE2S_184   '0xb257'"

.PP
Definition at line 225 of file codecs\&.h\&.
.SS "#define BLAKE2S_192   '0xb258'"

.PP
Definition at line 226 of file codecs\&.h\&.
.SS "#define BLAKE2S_200   '0xb259'"

.PP
Definition at line 227 of file codecs\&.h\&.
.SS "#define BLAKE2S_208   '0xb25a'"

.PP
Definition at line 228 of file codecs\&.h\&.
.SS "#define BLAKE2S_216   '0xb25b'"

.PP
Definition at line 229 of file codecs\&.h\&.
.SS "#define BLAKE2S_224   '0xb25c'"

.PP
Definition at line 230 of file codecs\&.h\&.
.SS "#define BLAKE2S_232   '0xb25d'"

.PP
Definition at line 231 of file codecs\&.h\&.
.SS "#define BLAKE2S_24   '0xb243'"

.PP
Definition at line 205 of file codecs\&.h\&.
.SS "#define BLAKE2S_240   '0xb25e'"

.PP
Definition at line 232 of file codecs\&.h\&.
.SS "#define BLAKE2S_248   '0xb25f'"

.PP
Definition at line 233 of file codecs\&.h\&.
.SS "#define BLAKE2S_256   '0xb260'"

.PP
Definition at line 234 of file codecs\&.h\&.
.SS "#define BLAKE2S_32   '0xb244'"

.PP
Definition at line 206 of file codecs\&.h\&.
.SS "#define BLAKE2S_40   '0xb245'"

.PP
Definition at line 207 of file codecs\&.h\&.
.SS "#define BLAKE2S_48   '0xb246'"

.PP
Definition at line 208 of file codecs\&.h\&.
.SS "#define BLAKE2S_56   '0xb247'"

.PP
Definition at line 209 of file codecs\&.h\&.
.SS "#define BLAKE2S_64   '0xb248'"

.PP
Definition at line 210 of file codecs\&.h\&.
.SS "#define BLAKE2S_72   '0xb249'"

.PP
Definition at line 211 of file codecs\&.h\&.
.SS "#define BLAKE2S_8   '0xb241'"

.PP
Definition at line 203 of file codecs\&.h\&.
.SS "#define BLAKE2S_80   '0xb24a'"

.PP
Definition at line 212 of file codecs\&.h\&.
.SS "#define BLAKE2S_88   '0xb24b'"

.PP
Definition at line 213 of file codecs\&.h\&.
.SS "#define BLAKE2S_96   '0xb24c'"

.PP
Definition at line 214 of file codecs\&.h\&.
.SS "#define BLAKE3   '0x1e'"

.PP
Definition at line 39 of file codecs\&.h\&.
.SS "#define BLS12_381_G1_PUB   '0xea'"

.PP
Definition at line 99 of file codecs\&.h\&.
.SS "#define BLS12_381_G2_PUB   '0xeb'"

.PP
Definition at line 100 of file codecs\&.h\&.
.SS "#define BMT   '0xd6'"

.PP
Definition at line 90 of file codecs\&.h\&.
.SS "#define CBOR   '0x51'"

.PP
Definition at line 55 of file codecs\&.h\&.
.SS "#define CODECS_COUNT   446"

.PP
Definition at line 469 of file codecs\&.h\&.
.SS "#define DAG_CBOR   '0x71'"

.PP
Definition at line 61 of file codecs\&.h\&.
.SS "#define DAG_COSE   '0x86'"

.PP
Definition at line 71 of file codecs\&.h\&.
.SS "#define DAG_JOSE   '0x85'"

.PP
Definition at line 70 of file codecs\&.h\&.
.SS "#define DAG_JSON   '0x0129'"

.PP
Definition at line 112 of file codecs\&.h\&.
.SS "#define DAG_PB   '0x70'"

.PP
Definition at line 60 of file codecs\&.h\&.
.SS "#define DASH_BLOCK   '0xf0'"

.PP
Definition at line 103 of file codecs\&.h\&.
.SS "#define DASH_TX   '0xf1'"

.PP
Definition at line 104 of file codecs\&.h\&.
.SS "#define DBL_SHA2_256   '0x56'"

.PP
Definition at line 57 of file codecs\&.h\&.
.SS "#define DCCP   '0x21'"

.PP
Definition at line 40 of file codecs\&.h\&.
.SS "#define DECRED_BLOCK   '0xe0'"

.PP
Definition at line 91 of file codecs\&.h\&.
.SS "#define DECRED_TX   '0xe1'"

.PP
Definition at line 92 of file codecs\&.h\&.
.SS "#define DNS   '0x35'"

.PP
Definition at line 50 of file codecs\&.h\&.
.SS "#define DNS4   '0x36'"

.PP
Definition at line 51 of file codecs\&.h\&.
.SS "#define DNS6   '0x37'"

.PP
Definition at line 52 of file codecs\&.h\&.
.SS "#define DNSADDR   '0x38'"

.PP
Definition at line 53 of file codecs\&.h\&.
.SS "#define ED25519_PUB   '0xed'"

.PP
Definition at line 102 of file codecs\&.h\&.
.SS "#define ETH_ACCOUNT_SNAPSHOT   '0x97'"

.PP
Definition at line 79 of file codecs\&.h\&.
.SS "#define ETH_BLOCK   '0x90'"

.PP
Definition at line 72 of file codecs\&.h\&.
.SS "#define ETH_BLOCK_LIST   '0x91'"

.PP
Definition at line 73 of file codecs\&.h\&.
.SS "#define ETH_STATE_TRIE   '0x96'"

.PP
Definition at line 78 of file codecs\&.h\&.
.SS "#define ETH_STORAGE_TRIE   '0x98'"

.PP
Definition at line 80 of file codecs\&.h\&.
.SS "#define ETH_TX   '0x93'"

.PP
Definition at line 75 of file codecs\&.h\&.
.SS "#define ETH_TX_RECEIPT   '0x95'"

.PP
Definition at line 77 of file codecs\&.h\&.
.SS "#define ETH_TX_RECEIPT_TRIE   '0x94'"

.PP
Definition at line 76 of file codecs\&.h\&.
.SS "#define ETH_TX_TRIE   '0x92'"

.PP
Definition at line 74 of file codecs\&.h\&.
.SS "#define FIL_COMMITMENT_SEALED   '0xf102'"

.PP
Definition at line 462 of file codecs\&.h\&.
.SS "#define FIL_COMMITMENT_UNSEALED   '0xf101'"

.PP
Definition at line 461 of file codecs\&.h\&.
.SS "#define GARLIC32   '0x01bf'"

.PP
Definition at line 122 of file codecs\&.h\&.
.SS "#define GARLIC64   '0x01be'"

.PP
Definition at line 121 of file codecs\&.h\&.
.SS "#define GIT_RAW   '0x78'"

.PP
Definition at line 63 of file codecs\&.h\&.
.SS "#define HOLOCHAIN_ADR_V0   '0x807124'"

.PP
Definition at line 463 of file codecs\&.h\&.
.SS "#define HOLOCHAIN_ADR_V1   '0x817124'"

.PP
Definition at line 464 of file codecs\&.h\&.
.SS "#define HOLOCHAIN_KEY_V0   '0x947124'"

.PP
Definition at line 465 of file codecs\&.h\&.
.SS "#define HOLOCHAIN_KEY_V1   '0x957124'"

.PP
Definition at line 466 of file codecs\&.h\&.
.SS "#define HOLOCHAIN_SIG_V0   '0xa27124'"

.PP
Definition at line 467 of file codecs\&.h\&.
.SS "#define HOLOCHAIN_SIG_V1   '0xa37124'"

.PP
Definition at line 468 of file codecs\&.h\&.
.SS "#define HTTP   '0x01e0'"

.PP
Definition at line 128 of file codecs\&.h\&.
.SS "#define HTTPS   '0x01bb'"

.PP
Definition at line 118 of file codecs\&.h\&.
.SS "#define IDENTITY   '0x00'"

.PP
Definition at line 23 of file codecs\&.h\&.
.SS "#define IP4   '0x04'"

.PP
Definition at line 24 of file codecs\&.h\&.
.SS "#define IP6   '0x29'"

.PP
Definition at line 43 of file codecs\&.h\&.
.SS "#define IP6ZONE   '0x2a'"

.PP
Definition at line 44 of file codecs\&.h\&.
.SS "#define IPFS   '0x01a5'"

.PP
Definition at line 117 of file codecs\&.h\&.
.SS "#define IPFS_NS   '0xe3'"

.PP
Definition at line 94 of file codecs\&.h\&.
.SS "#define IPLD_NS   '0xe2'"

.PP
Definition at line 93 of file codecs\&.h\&.
.SS "#define IPNS_NS   '0xe5'"

.PP
Definition at line 96 of file codecs\&.h\&.
.SS "#define JSON   '0x0200'"

.PP
Definition at line 129 of file codecs\&.h\&.
.SS "#define KECCAK_224   '0x1a'"

.PP
Definition at line 35 of file codecs\&.h\&.
.SS "#define KECCAK_256   '0x1b'"

.PP
Definition at line 36 of file codecs\&.h\&.
.SS "#define KECCAK_384   '0x1c'"

.PP
Definition at line 37 of file codecs\&.h\&.
.SS "#define KECCAK_512   '0x1d'"

.PP
Definition at line 38 of file codecs\&.h\&.
.SS "#define LEOFCOIN_BLOCK   '0x81'"

.PP
Definition at line 66 of file codecs\&.h\&.
.SS "#define LEOFCOIN_PR   '0x83'"

.PP
Definition at line 68 of file codecs\&.h\&.
.SS "#define LEOFCOIN_TX   '0x82'"

.PP
Definition at line 67 of file codecs\&.h\&.
.SS "#define LIBP2P_KEY   '0x72'"

.PP
Definition at line 62 of file codecs\&.h\&.
.SS "#define LIBP2P_PEER_RECORD   '0x0301'"

.PP
Definition at line 131 of file codecs\&.h\&.
.SS "#define MD4   '0xd4'"

.PP
Definition at line 88 of file codecs\&.h\&.
.SS "#define MD5   '0xd5'"

.PP
Definition at line 89 of file codecs\&.h\&.
.SS "#define MESSAGEPACK   '0x0201'"

.PP
Definition at line 130 of file codecs\&.h\&.
.SS "#define MULTIADDR   '0x32'"

.PP
Definition at line 48 of file codecs\&.h\&.
.SS "#define MULTIBASE   '0x33'"

.PP
Definition at line 49 of file codecs\&.h\&.
.SS "#define MULTICODEC   '0x30'"

.PP
Definition at line 46 of file codecs\&.h\&.
.SS "#define MULTIHASH   '0x31'"

.PP
Definition at line 47 of file codecs\&.h\&.
.SS "#define MURMUR3_128   '0x22'"

.PP
Definition at line 41 of file codecs\&.h\&.
.SS "#define MURMUR3_32   '0x23'"

.PP
Definition at line 42 of file codecs\&.h\&.
.SS "#define ONION   '0x01bc'"

.PP
Definition at line 119 of file codecs\&.h\&.
.SS "#define ONION3   '0x01bd'"

.PP
Definition at line 120 of file codecs\&.h\&.
.SS "#define P2P   '0x01a5'"

.PP
Definition at line 116 of file codecs\&.h\&.
.SS "#define P2P_CIRCUIT   '0x0122'"

.PP
Definition at line 111 of file codecs\&.h\&.
.SS "#define P2P_STARDUST   '0x0115'"

.PP
Definition at line 110 of file codecs\&.h\&.
.SS "#define P2P_WEBRTC_DIRECT   '0x0114'"

.PP
Definition at line 109 of file codecs\&.h\&.
.SS "#define P2P_WEBRTC_STAR   '0x0113'"

.PP
Definition at line 108 of file codecs\&.h\&.
.SS "#define P2P_WEBSOCKET_STAR   '0x01df'"

.PP
Definition at line 127 of file codecs\&.h\&.
.SS "#define PATH   '0x2f'"

.PP
Definition at line 45 of file codecs\&.h\&.
.SS "#define POSEIDON_BLS12_381_A2_FC1   '0xb401'"

.PP
Definition at line 459 of file codecs\&.h\&.
.SS "#define POSEIDON_BLS12_381_A2_FC1_SC   '0xb402'"

.PP
Definition at line 460 of file codecs\&.h\&.
.SS "#define PROTOBUF   '0x50'"

.PP
Definition at line 54 of file codecs\&.h\&.
.SS "#define QUIC   '0x01cc'"

.PP
Definition at line 124 of file codecs\&.h\&.
.SS "#define RAW   '0x55'"

.PP
Definition at line 56 of file codecs\&.h\&.
.SS "#define RIPEMD_128   '0x1052'"

.PP
Definition at line 133 of file codecs\&.h\&.
.SS "#define RIPEMD_160   '0x1053'"

.PP
Definition at line 134 of file codecs\&.h\&.
.SS "#define RIPEMD_256   '0x1054'"

.PP
Definition at line 135 of file codecs\&.h\&.
.SS "#define RIPEMD_320   '0x1055'"

.PP
Definition at line 136 of file codecs\&.h\&.
.SS "#define RLP   '0x60'"

.PP
Definition at line 58 of file codecs\&.h\&.
.SS "#define SCTP   '0x84'"

.PP
Definition at line 69 of file codecs\&.h\&.
.SS "#define SECP256K1_PUB   '0xe7'"

.PP
Definition at line 98 of file codecs\&.h\&.
.SS "#define SHA1   '0x11'"

.PP
Definition at line 26 of file codecs\&.h\&.
.SS "#define SHA2_256   '0x12'"

.PP
Definition at line 27 of file codecs\&.h\&.
.SS "#define SHA2_256_TRUNC254_PADDED   '0x1012'"

.PP
Definition at line 132 of file codecs\&.h\&.
.SS "#define SHA2_512   '0x13'"

.PP
Definition at line 28 of file codecs\&.h\&.
.SS "#define SHA3_224   '0x17'"

.PP
Definition at line 32 of file codecs\&.h\&.
.SS "#define SHA3_256   '0x16'"

.PP
Definition at line 31 of file codecs\&.h\&.
.SS "#define SHA3_384   '0x15'"

.PP
Definition at line 30 of file codecs\&.h\&.
.SS "#define SHA3_512   '0x14'"

.PP
Definition at line 29 of file codecs\&.h\&.
.SS "#define SHAKE_128   '0x18'"

.PP
Definition at line 33 of file codecs\&.h\&.
.SS "#define SHAKE_256   '0x19'"

.PP
Definition at line 34 of file codecs\&.h\&.
.SS "#define SKEIN1024_1000   '0xb3dd'"

.PP
Definition at line 455 of file codecs\&.h\&.
.SS "#define SKEIN1024_1008   '0xb3de'"

.PP
Definition at line 456 of file codecs\&.h\&.
.SS "#define SKEIN1024_1016   '0xb3df'"

.PP
Definition at line 457 of file codecs\&.h\&.
.SS "#define SKEIN1024_1024   '0xb3e0'"

.PP
Definition at line 458 of file codecs\&.h\&.
.SS "#define SKEIN1024_104   '0xb36d'"

.PP
Definition at line 343 of file codecs\&.h\&.
.SS "#define SKEIN1024_112   '0xb36e'"

.PP
Definition at line 344 of file codecs\&.h\&.
.SS "#define SKEIN1024_120   '0xb36f'"

.PP
Definition at line 345 of file codecs\&.h\&.
.SS "#define SKEIN1024_128   '0xb370'"

.PP
Definition at line 346 of file codecs\&.h\&.
.SS "#define SKEIN1024_136   '0xb371'"

.PP
Definition at line 347 of file codecs\&.h\&.
.SS "#define SKEIN1024_144   '0xb372'"

.PP
Definition at line 348 of file codecs\&.h\&.
.SS "#define SKEIN1024_152   '0xb373'"

.PP
Definition at line 349 of file codecs\&.h\&.
.SS "#define SKEIN1024_16   '0xb362'"

.PP
Definition at line 332 of file codecs\&.h\&.
.SS "#define SKEIN1024_160   '0xb374'"

.PP
Definition at line 350 of file codecs\&.h\&.
.SS "#define SKEIN1024_168   '0xb375'"

.PP
Definition at line 351 of file codecs\&.h\&.
.SS "#define SKEIN1024_176   '0xb376'"

.PP
Definition at line 352 of file codecs\&.h\&.
.SS "#define SKEIN1024_184   '0xb377'"

.PP
Definition at line 353 of file codecs\&.h\&.
.SS "#define SKEIN1024_192   '0xb378'"

.PP
Definition at line 354 of file codecs\&.h\&.
.SS "#define SKEIN1024_200   '0xb379'"

.PP
Definition at line 355 of file codecs\&.h\&.
.SS "#define SKEIN1024_208   '0xb37a'"

.PP
Definition at line 356 of file codecs\&.h\&.
.SS "#define SKEIN1024_216   '0xb37b'"

.PP
Definition at line 357 of file codecs\&.h\&.
.SS "#define SKEIN1024_224   '0xb37c'"

.PP
Definition at line 358 of file codecs\&.h\&.
.SS "#define SKEIN1024_232   '0xb37d'"

.PP
Definition at line 359 of file codecs\&.h\&.
.SS "#define SKEIN1024_24   '0xb363'"

.PP
Definition at line 333 of file codecs\&.h\&.
.SS "#define SKEIN1024_240   '0xb37e'"

.PP
Definition at line 360 of file codecs\&.h\&.
.SS "#define SKEIN1024_248   '0xb37f'"

.PP
Definition at line 361 of file codecs\&.h\&.
.SS "#define SKEIN1024_256   '0xb380'"

.PP
Definition at line 362 of file codecs\&.h\&.
.SS "#define SKEIN1024_264   '0xb381'"

.PP
Definition at line 363 of file codecs\&.h\&.
.SS "#define SKEIN1024_272   '0xb382'"

.PP
Definition at line 364 of file codecs\&.h\&.
.SS "#define SKEIN1024_280   '0xb383'"

.PP
Definition at line 365 of file codecs\&.h\&.
.SS "#define SKEIN1024_288   '0xb384'"

.PP
Definition at line 366 of file codecs\&.h\&.
.SS "#define SKEIN1024_296   '0xb385'"

.PP
Definition at line 367 of file codecs\&.h\&.
.SS "#define SKEIN1024_304   '0xb386'"

.PP
Definition at line 368 of file codecs\&.h\&.
.SS "#define SKEIN1024_312   '0xb387'"

.PP
Definition at line 369 of file codecs\&.h\&.
.SS "#define SKEIN1024_32   '0xb364'"

.PP
Definition at line 334 of file codecs\&.h\&.
.SS "#define SKEIN1024_320   '0xb388'"

.PP
Definition at line 370 of file codecs\&.h\&.
.SS "#define SKEIN1024_328   '0xb389'"

.PP
Definition at line 371 of file codecs\&.h\&.
.SS "#define SKEIN1024_336   '0xb38a'"

.PP
Definition at line 372 of file codecs\&.h\&.
.SS "#define SKEIN1024_344   '0xb38b'"

.PP
Definition at line 373 of file codecs\&.h\&.
.SS "#define SKEIN1024_352   '0xb38c'"

.PP
Definition at line 374 of file codecs\&.h\&.
.SS "#define SKEIN1024_360   '0xb38d'"

.PP
Definition at line 375 of file codecs\&.h\&.
.SS "#define SKEIN1024_368   '0xb38e'"

.PP
Definition at line 376 of file codecs\&.h\&.
.SS "#define SKEIN1024_376   '0xb38f'"

.PP
Definition at line 377 of file codecs\&.h\&.
.SS "#define SKEIN1024_384   '0xb390'"

.PP
Definition at line 378 of file codecs\&.h\&.
.SS "#define SKEIN1024_392   '0xb391'"

.PP
Definition at line 379 of file codecs\&.h\&.
.SS "#define SKEIN1024_40   '0xb365'"

.PP
Definition at line 335 of file codecs\&.h\&.
.SS "#define SKEIN1024_400   '0xb392'"

.PP
Definition at line 380 of file codecs\&.h\&.
.SS "#define SKEIN1024_408   '0xb393'"

.PP
Definition at line 381 of file codecs\&.h\&.
.SS "#define SKEIN1024_416   '0xb394'"

.PP
Definition at line 382 of file codecs\&.h\&.
.SS "#define SKEIN1024_424   '0xb395'"

.PP
Definition at line 383 of file codecs\&.h\&.
.SS "#define SKEIN1024_432   '0xb396'"

.PP
Definition at line 384 of file codecs\&.h\&.
.SS "#define SKEIN1024_440   '0xb397'"

.PP
Definition at line 385 of file codecs\&.h\&.
.SS "#define SKEIN1024_448   '0xb398'"

.PP
Definition at line 386 of file codecs\&.h\&.
.SS "#define SKEIN1024_456   '0xb399'"

.PP
Definition at line 387 of file codecs\&.h\&.
.SS "#define SKEIN1024_464   '0xb39a'"

.PP
Definition at line 388 of file codecs\&.h\&.
.SS "#define SKEIN1024_472   '0xb39b'"

.PP
Definition at line 389 of file codecs\&.h\&.
.SS "#define SKEIN1024_48   '0xb366'"

.PP
Definition at line 336 of file codecs\&.h\&.
.SS "#define SKEIN1024_480   '0xb39c'"

.PP
Definition at line 390 of file codecs\&.h\&.
.SS "#define SKEIN1024_488   '0xb39d'"

.PP
Definition at line 391 of file codecs\&.h\&.
.SS "#define SKEIN1024_496   '0xb39e'"

.PP
Definition at line 392 of file codecs\&.h\&.
.SS "#define SKEIN1024_504   '0xb39f'"

.PP
Definition at line 393 of file codecs\&.h\&.
.SS "#define SKEIN1024_512   '0xb3a0'"

.PP
Definition at line 394 of file codecs\&.h\&.
.SS "#define SKEIN1024_520   '0xb3a1'"

.PP
Definition at line 395 of file codecs\&.h\&.
.SS "#define SKEIN1024_528   '0xb3a2'"

.PP
Definition at line 396 of file codecs\&.h\&.
.SS "#define SKEIN1024_536   '0xb3a3'"

.PP
Definition at line 397 of file codecs\&.h\&.
.SS "#define SKEIN1024_544   '0xb3a4'"

.PP
Definition at line 398 of file codecs\&.h\&.
.SS "#define SKEIN1024_552   '0xb3a5'"

.PP
Definition at line 399 of file codecs\&.h\&.
.SS "#define SKEIN1024_56   '0xb367'"

.PP
Definition at line 337 of file codecs\&.h\&.
.SS "#define SKEIN1024_560   '0xb3a6'"

.PP
Definition at line 400 of file codecs\&.h\&.
.SS "#define SKEIN1024_568   '0xb3a7'"

.PP
Definition at line 401 of file codecs\&.h\&.
.SS "#define SKEIN1024_576   '0xb3a8'"

.PP
Definition at line 402 of file codecs\&.h\&.
.SS "#define SKEIN1024_584   '0xb3a9'"

.PP
Definition at line 403 of file codecs\&.h\&.
.SS "#define SKEIN1024_592   '0xb3aa'"

.PP
Definition at line 404 of file codecs\&.h\&.
.SS "#define SKEIN1024_600   '0xb3ab'"

.PP
Definition at line 405 of file codecs\&.h\&.
.SS "#define SKEIN1024_608   '0xb3ac'"

.PP
Definition at line 406 of file codecs\&.h\&.
.SS "#define SKEIN1024_616   '0xb3ad'"

.PP
Definition at line 407 of file codecs\&.h\&.
.SS "#define SKEIN1024_624   '0xb3ae'"

.PP
Definition at line 408 of file codecs\&.h\&.
.SS "#define SKEIN1024_632   '0xb3af'"

.PP
Definition at line 409 of file codecs\&.h\&.
.SS "#define SKEIN1024_64   '0xb368'"

.PP
Definition at line 338 of file codecs\&.h\&.
.SS "#define SKEIN1024_640   '0xb3b0'"

.PP
Definition at line 410 of file codecs\&.h\&.
.SS "#define SKEIN1024_648   '0xb3b1'"

.PP
Definition at line 411 of file codecs\&.h\&.
.SS "#define SKEIN1024_656   '0xb3b2'"

.PP
Definition at line 412 of file codecs\&.h\&.
.SS "#define SKEIN1024_664   '0xb3b3'"

.PP
Definition at line 413 of file codecs\&.h\&.
.SS "#define SKEIN1024_672   '0xb3b4'"

.PP
Definition at line 414 of file codecs\&.h\&.
.SS "#define SKEIN1024_680   '0xb3b5'"

.PP
Definition at line 415 of file codecs\&.h\&.
.SS "#define SKEIN1024_688   '0xb3b6'"

.PP
Definition at line 416 of file codecs\&.h\&.
.SS "#define SKEIN1024_696   '0xb3b7'"

.PP
Definition at line 417 of file codecs\&.h\&.
.SS "#define SKEIN1024_704   '0xb3b8'"

.PP
Definition at line 418 of file codecs\&.h\&.
.SS "#define SKEIN1024_712   '0xb3b9'"

.PP
Definition at line 419 of file codecs\&.h\&.
.SS "#define SKEIN1024_72   '0xb369'"

.PP
Definition at line 339 of file codecs\&.h\&.
.SS "#define SKEIN1024_720   '0xb3ba'"

.PP
Definition at line 420 of file codecs\&.h\&.
.SS "#define SKEIN1024_728   '0xb3bb'"

.PP
Definition at line 421 of file codecs\&.h\&.
.SS "#define SKEIN1024_736   '0xb3bc'"

.PP
Definition at line 422 of file codecs\&.h\&.
.SS "#define SKEIN1024_744   '0xb3bd'"

.PP
Definition at line 423 of file codecs\&.h\&.
.SS "#define SKEIN1024_752   '0xb3be'"

.PP
Definition at line 424 of file codecs\&.h\&.
.SS "#define SKEIN1024_760   '0xb3bf'"

.PP
Definition at line 425 of file codecs\&.h\&.
.SS "#define SKEIN1024_768   '0xb3c0'"

.PP
Definition at line 426 of file codecs\&.h\&.
.SS "#define SKEIN1024_776   '0xb3c1'"

.PP
Definition at line 427 of file codecs\&.h\&.
.SS "#define SKEIN1024_784   '0xb3c2'"

.PP
Definition at line 428 of file codecs\&.h\&.
.SS "#define SKEIN1024_792   '0xb3c3'"

.PP
Definition at line 429 of file codecs\&.h\&.
.SS "#define SKEIN1024_8   '0xb361'"

.PP
Definition at line 331 of file codecs\&.h\&.
.SS "#define SKEIN1024_80   '0xb36a'"

.PP
Definition at line 340 of file codecs\&.h\&.
.SS "#define SKEIN1024_800   '0xb3c4'"

.PP
Definition at line 430 of file codecs\&.h\&.
.SS "#define SKEIN1024_808   '0xb3c5'"

.PP
Definition at line 431 of file codecs\&.h\&.
.SS "#define SKEIN1024_816   '0xb3c6'"

.PP
Definition at line 432 of file codecs\&.h\&.
.SS "#define SKEIN1024_824   '0xb3c7'"

.PP
Definition at line 433 of file codecs\&.h\&.
.SS "#define SKEIN1024_832   '0xb3c8'"

.PP
Definition at line 434 of file codecs\&.h\&.
.SS "#define SKEIN1024_840   '0xb3c9'"

.PP
Definition at line 435 of file codecs\&.h\&.
.SS "#define SKEIN1024_848   '0xb3ca'"

.PP
Definition at line 436 of file codecs\&.h\&.
.SS "#define SKEIN1024_856   '0xb3cb'"

.PP
Definition at line 437 of file codecs\&.h\&.
.SS "#define SKEIN1024_864   '0xb3cc'"

.PP
Definition at line 438 of file codecs\&.h\&.
.SS "#define SKEIN1024_872   '0xb3cd'"

.PP
Definition at line 439 of file codecs\&.h\&.
.SS "#define SKEIN1024_88   '0xb36b'"

.PP
Definition at line 341 of file codecs\&.h\&.
.SS "#define SKEIN1024_880   '0xb3ce'"

.PP
Definition at line 440 of file codecs\&.h\&.
.SS "#define SKEIN1024_888   '0xb3cf'"

.PP
Definition at line 441 of file codecs\&.h\&.
.SS "#define SKEIN1024_896   '0xb3d0'"

.PP
Definition at line 442 of file codecs\&.h\&.
.SS "#define SKEIN1024_904   '0xb3d1'"

.PP
Definition at line 443 of file codecs\&.h\&.
.SS "#define SKEIN1024_912   '0xb3d2'"

.PP
Definition at line 444 of file codecs\&.h\&.
.SS "#define SKEIN1024_920   '0xb3d3'"

.PP
Definition at line 445 of file codecs\&.h\&.
.SS "#define SKEIN1024_928   '0xb3d4'"

.PP
Definition at line 446 of file codecs\&.h\&.
.SS "#define SKEIN1024_936   '0xb3d5'"

.PP
Definition at line 447 of file codecs\&.h\&.
.SS "#define SKEIN1024_944   '0xb3d6'"

.PP
Definition at line 448 of file codecs\&.h\&.
.SS "#define SKEIN1024_952   '0xb3d7'"

.PP
Definition at line 449 of file codecs\&.h\&.
.SS "#define SKEIN1024_96   '0xb36c'"

.PP
Definition at line 342 of file codecs\&.h\&.
.SS "#define SKEIN1024_960   '0xb3d8'"

.PP
Definition at line 450 of file codecs\&.h\&.
.SS "#define SKEIN1024_968   '0xb3d9'"

.PP
Definition at line 451 of file codecs\&.h\&.
.SS "#define SKEIN1024_976   '0xb3da'"

.PP
Definition at line 452 of file codecs\&.h\&.
.SS "#define SKEIN1024_984   '0xb3db'"

.PP
Definition at line 453 of file codecs\&.h\&.
.SS "#define SKEIN1024_992   '0xb3dc'"

.PP
Definition at line 454 of file codecs\&.h\&.
.SS "#define SKEIN256_104   '0xb30d'"

.PP
Definition at line 247 of file codecs\&.h\&.
.SS "#define SKEIN256_112   '0xb30e'"

.PP
Definition at line 248 of file codecs\&.h\&.
.SS "#define SKEIN256_120   '0xb30f'"

.PP
Definition at line 249 of file codecs\&.h\&.
.SS "#define SKEIN256_128   '0xb310'"

.PP
Definition at line 250 of file codecs\&.h\&.
.SS "#define SKEIN256_136   '0xb311'"

.PP
Definition at line 251 of file codecs\&.h\&.
.SS "#define SKEIN256_144   '0xb312'"

.PP
Definition at line 252 of file codecs\&.h\&.
.SS "#define SKEIN256_152   '0xb313'"

.PP
Definition at line 253 of file codecs\&.h\&.
.SS "#define SKEIN256_16   '0xb302'"

.PP
Definition at line 236 of file codecs\&.h\&.
.SS "#define SKEIN256_160   '0xb314'"

.PP
Definition at line 254 of file codecs\&.h\&.
.SS "#define SKEIN256_168   '0xb315'"

.PP
Definition at line 255 of file codecs\&.h\&.
.SS "#define SKEIN256_176   '0xb316'"

.PP
Definition at line 256 of file codecs\&.h\&.
.SS "#define SKEIN256_184   '0xb317'"

.PP
Definition at line 257 of file codecs\&.h\&.
.SS "#define SKEIN256_192   '0xb318'"

.PP
Definition at line 258 of file codecs\&.h\&.
.SS "#define SKEIN256_200   '0xb319'"

.PP
Definition at line 259 of file codecs\&.h\&.
.SS "#define SKEIN256_208   '0xb31a'"

.PP
Definition at line 260 of file codecs\&.h\&.
.SS "#define SKEIN256_216   '0xb31b'"

.PP
Definition at line 261 of file codecs\&.h\&.
.SS "#define SKEIN256_224   '0xb31c'"

.PP
Definition at line 262 of file codecs\&.h\&.
.SS "#define SKEIN256_232   '0xb31d'"

.PP
Definition at line 263 of file codecs\&.h\&.
.SS "#define SKEIN256_24   '0xb303'"

.PP
Definition at line 237 of file codecs\&.h\&.
.SS "#define SKEIN256_240   '0xb31e'"

.PP
Definition at line 264 of file codecs\&.h\&.
.SS "#define SKEIN256_248   '0xb31f'"

.PP
Definition at line 265 of file codecs\&.h\&.
.SS "#define SKEIN256_256   '0xb320'"

.PP
Definition at line 266 of file codecs\&.h\&.
.SS "#define SKEIN256_32   '0xb304'"

.PP
Definition at line 238 of file codecs\&.h\&.
.SS "#define SKEIN256_40   '0xb305'"

.PP
Definition at line 239 of file codecs\&.h\&.
.SS "#define SKEIN256_48   '0xb306'"

.PP
Definition at line 240 of file codecs\&.h\&.
.SS "#define SKEIN256_56   '0xb307'"

.PP
Definition at line 241 of file codecs\&.h\&.
.SS "#define SKEIN256_64   '0xb308'"

.PP
Definition at line 242 of file codecs\&.h\&.
.SS "#define SKEIN256_72   '0xb309'"

.PP
Definition at line 243 of file codecs\&.h\&.
.SS "#define SKEIN256_8   '0xb301'"

.PP
Definition at line 235 of file codecs\&.h\&.
.SS "#define SKEIN256_80   '0xb30a'"

.PP
Definition at line 244 of file codecs\&.h\&.
.SS "#define SKEIN256_88   '0xb30b'"

.PP
Definition at line 245 of file codecs\&.h\&.
.SS "#define SKEIN256_96   '0xb30c'"

.PP
Definition at line 246 of file codecs\&.h\&.
.SS "#define SKEIN512_104   '0xb32d'"

.PP
Definition at line 279 of file codecs\&.h\&.
.SS "#define SKEIN512_112   '0xb32e'"

.PP
Definition at line 280 of file codecs\&.h\&.
.SS "#define SKEIN512_120   '0xb32f'"

.PP
Definition at line 281 of file codecs\&.h\&.
.SS "#define SKEIN512_128   '0xb330'"

.PP
Definition at line 282 of file codecs\&.h\&.
.SS "#define SKEIN512_136   '0xb331'"

.PP
Definition at line 283 of file codecs\&.h\&.
.SS "#define SKEIN512_144   '0xb332'"

.PP
Definition at line 284 of file codecs\&.h\&.
.SS "#define SKEIN512_152   '0xb333'"

.PP
Definition at line 285 of file codecs\&.h\&.
.SS "#define SKEIN512_16   '0xb322'"

.PP
Definition at line 268 of file codecs\&.h\&.
.SS "#define SKEIN512_160   '0xb334'"

.PP
Definition at line 286 of file codecs\&.h\&.
.SS "#define SKEIN512_168   '0xb335'"

.PP
Definition at line 287 of file codecs\&.h\&.
.SS "#define SKEIN512_176   '0xb336'"

.PP
Definition at line 288 of file codecs\&.h\&.
.SS "#define SKEIN512_184   '0xb337'"

.PP
Definition at line 289 of file codecs\&.h\&.
.SS "#define SKEIN512_192   '0xb338'"

.PP
Definition at line 290 of file codecs\&.h\&.
.SS "#define SKEIN512_200   '0xb339'"

.PP
Definition at line 291 of file codecs\&.h\&.
.SS "#define SKEIN512_208   '0xb33a'"

.PP
Definition at line 292 of file codecs\&.h\&.
.SS "#define SKEIN512_216   '0xb33b'"

.PP
Definition at line 293 of file codecs\&.h\&.
.SS "#define SKEIN512_224   '0xb33c'"

.PP
Definition at line 294 of file codecs\&.h\&.
.SS "#define SKEIN512_232   '0xb33d'"

.PP
Definition at line 295 of file codecs\&.h\&.
.SS "#define SKEIN512_24   '0xb323'"

.PP
Definition at line 269 of file codecs\&.h\&.
.SS "#define SKEIN512_240   '0xb33e'"

.PP
Definition at line 296 of file codecs\&.h\&.
.SS "#define SKEIN512_248   '0xb33f'"

.PP
Definition at line 297 of file codecs\&.h\&.
.SS "#define SKEIN512_256   '0xb340'"

.PP
Definition at line 298 of file codecs\&.h\&.
.SS "#define SKEIN512_264   '0xb341'"

.PP
Definition at line 299 of file codecs\&.h\&.
.SS "#define SKEIN512_272   '0xb342'"

.PP
Definition at line 300 of file codecs\&.h\&.
.SS "#define SKEIN512_280   '0xb343'"

.PP
Definition at line 301 of file codecs\&.h\&.
.SS "#define SKEIN512_288   '0xb344'"

.PP
Definition at line 302 of file codecs\&.h\&.
.SS "#define SKEIN512_296   '0xb345'"

.PP
Definition at line 303 of file codecs\&.h\&.
.SS "#define SKEIN512_304   '0xb346'"

.PP
Definition at line 304 of file codecs\&.h\&.
.SS "#define SKEIN512_312   '0xb347'"

.PP
Definition at line 305 of file codecs\&.h\&.
.SS "#define SKEIN512_32   '0xb324'"

.PP
Definition at line 270 of file codecs\&.h\&.
.SS "#define SKEIN512_320   '0xb348'"

.PP
Definition at line 306 of file codecs\&.h\&.
.SS "#define SKEIN512_328   '0xb349'"

.PP
Definition at line 307 of file codecs\&.h\&.
.SS "#define SKEIN512_336   '0xb34a'"

.PP
Definition at line 308 of file codecs\&.h\&.
.SS "#define SKEIN512_344   '0xb34b'"

.PP
Definition at line 309 of file codecs\&.h\&.
.SS "#define SKEIN512_352   '0xb34c'"

.PP
Definition at line 310 of file codecs\&.h\&.
.SS "#define SKEIN512_360   '0xb34d'"

.PP
Definition at line 311 of file codecs\&.h\&.
.SS "#define SKEIN512_368   '0xb34e'"

.PP
Definition at line 312 of file codecs\&.h\&.
.SS "#define SKEIN512_376   '0xb34f'"

.PP
Definition at line 313 of file codecs\&.h\&.
.SS "#define SKEIN512_384   '0xb350'"

.PP
Definition at line 314 of file codecs\&.h\&.
.SS "#define SKEIN512_392   '0xb351'"

.PP
Definition at line 315 of file codecs\&.h\&.
.SS "#define SKEIN512_40   '0xb325'"

.PP
Definition at line 271 of file codecs\&.h\&.
.SS "#define SKEIN512_400   '0xb352'"

.PP
Definition at line 316 of file codecs\&.h\&.
.SS "#define SKEIN512_408   '0xb353'"

.PP
Definition at line 317 of file codecs\&.h\&.
.SS "#define SKEIN512_416   '0xb354'"

.PP
Definition at line 318 of file codecs\&.h\&.
.SS "#define SKEIN512_424   '0xb355'"

.PP
Definition at line 319 of file codecs\&.h\&.
.SS "#define SKEIN512_432   '0xb356'"

.PP
Definition at line 320 of file codecs\&.h\&.
.SS "#define SKEIN512_440   '0xb357'"

.PP
Definition at line 321 of file codecs\&.h\&.
.SS "#define SKEIN512_448   '0xb358'"

.PP
Definition at line 322 of file codecs\&.h\&.
.SS "#define SKEIN512_456   '0xb359'"

.PP
Definition at line 323 of file codecs\&.h\&.
.SS "#define SKEIN512_464   '0xb35a'"

.PP
Definition at line 324 of file codecs\&.h\&.
.SS "#define SKEIN512_472   '0xb35b'"

.PP
Definition at line 325 of file codecs\&.h\&.
.SS "#define SKEIN512_48   '0xb326'"

.PP
Definition at line 272 of file codecs\&.h\&.
.SS "#define SKEIN512_480   '0xb35c'"

.PP
Definition at line 326 of file codecs\&.h\&.
.SS "#define SKEIN512_488   '0xb35d'"

.PP
Definition at line 327 of file codecs\&.h\&.
.SS "#define SKEIN512_496   '0xb35e'"

.PP
Definition at line 328 of file codecs\&.h\&.
.SS "#define SKEIN512_504   '0xb35f'"

.PP
Definition at line 329 of file codecs\&.h\&.
.SS "#define SKEIN512_512   '0xb360'"

.PP
Definition at line 330 of file codecs\&.h\&.
.SS "#define SKEIN512_56   '0xb327'"

.PP
Definition at line 273 of file codecs\&.h\&.
.SS "#define SKEIN512_64   '0xb328'"

.PP
Definition at line 274 of file codecs\&.h\&.
.SS "#define SKEIN512_72   '0xb329'"

.PP
Definition at line 275 of file codecs\&.h\&.
.SS "#define SKEIN512_8   '0xb321'"

.PP
Definition at line 267 of file codecs\&.h\&.
.SS "#define SKEIN512_80   '0xb32a'"

.PP
Definition at line 276 of file codecs\&.h\&.
.SS "#define SKEIN512_88   '0xb32b'"

.PP
Definition at line 277 of file codecs\&.h\&.
.SS "#define SKEIN512_96   '0xb32c'"

.PP
Definition at line 278 of file codecs\&.h\&.
.SS "#define SM3_256   '0x534d'"

.PP
Definition at line 138 of file codecs\&.h\&.
.SS "#define STELLAR_BLOCK   '0xd0'"

.PP
Definition at line 86 of file codecs\&.h\&.
.SS "#define STELLAR_TX   '0xd1'"

.PP
Definition at line 87 of file codecs\&.h\&.
.SS "#define SWARM_FEED   '0xfb'"

.PP
Definition at line 106 of file codecs\&.h\&.
.SS "#define SWARM_MANIFEST   '0xfa'"

.PP
Definition at line 105 of file codecs\&.h\&.
.SS "#define SWARM_NS   '0xe4'"

.PP
Definition at line 95 of file codecs\&.h\&.
.SS "#define TCP   '0x06'"

.PP
Definition at line 25 of file codecs\&.h\&.
.SS "#define TLS   '0x01c0'"

.PP
Definition at line 123 of file codecs\&.h\&.
.SS "#define TORRENT_FILE   '0x7c'"

.PP
Definition at line 65 of file codecs\&.h\&.
.SS "#define TORRENT_INFO   '0x7b'"

.PP
Definition at line 64 of file codecs\&.h\&.
.SS "#define UDP   '0x0111'"

.PP
Definition at line 107 of file codecs\&.h\&.
.SS "#define UDT   '0x012d'"

.PP
Definition at line 113 of file codecs\&.h\&.
.SS "#define UNIX   '0x0190'"

.PP
Definition at line 115 of file codecs\&.h\&.
.SS "#define UTP   '0x012e'"

.PP
Definition at line 114 of file codecs\&.h\&.
.SS "#define WS   '0x01dd'"

.PP
Definition at line 125 of file codecs\&.h\&.
.SS "#define WSS   '0x01de'"

.PP
Definition at line 126 of file codecs\&.h\&.
.SS "#define X11   '0x1100'"

.PP
Definition at line 137 of file codecs\&.h\&.
.SS "#define X25519_PUB   '0xec'"

.PP
Definition at line 101 of file codecs\&.h\&.
.SS "#define ZCASH_BLOCK   '0xc0'"

.PP
Definition at line 84 of file codecs\&.h\&.
.SS "#define ZCASH_TX   '0xc1'"

.PP
Definition at line 85 of file codecs\&.h\&.
.SS "#define ZERONET   '0xe6'"

.PP
Definition at line 97 of file codecs\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const char* CODECS_LIST[]"

.PP
Definition at line 29 of file multicodec\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
