.TH "command" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <command_line\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcommand_count\fP"
.br
.ti -1c
.RI "int \fBargc\fP"
.br
.ti -1c
.RI "char * \fBargv\fP [32]"
.br
.ti -1c
.RI "\fBcommand_handler\fP * \fBcommands\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file command_line\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int command::argc"

.PP
Definition at line 52 of file command_line\&.h\&.
.SS "char* command::argv[32]"

.PP
Definition at line 53 of file command_line\&.h\&.
.SS "int command::command_count"

.PP
Definition at line 51 of file command_line\&.h\&.
.SS "\fBcommand_handler\fP* command::commands[32]"

.PP
Definition at line 54 of file command_line\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
