.TH "command_handler" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
command_handler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <command_line\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBcommand_handler_callback\fP \fBcallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file command_line\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBcommand_handler_callback\fP command_handler::callback"

.PP
Definition at line 44 of file command_line\&.h\&.
.SS "char* command_handler::name"

.PP
Definition at line 43 of file command_line\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
