.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/docs/conf.py" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/docs/conf.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconf\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBconf\&.extensions\fP = []"
.br
.ti -1c
.RI "list \fBconf\&.templates_path\fP = ['_templates']"
.br
.ti -1c
.RI "string \fBconf\&.source_suffix\fP = '\&.rst'"
.br
.ti -1c
.RI "string \fBconf\&.master_doc\fP = 'index'"
.br
.ti -1c
.RI "string \fBconf\&.project\fP = 'c\-template\-REPLACEME'"
.br
.ti -1c
.RI "string \fBconf\&.copyright\fP = '2020 c\-template\-REPLACEME'"
.br
.ti -1c
.RI "string \fBconf\&.author\fP = 'c\-template\-REPLACEME'"
.br
.ti -1c
.RI "string \fBconf\&.version\fP = ''"
.br
.ti -1c
.RI "string \fBconf\&.release\fP = ''"
.br
.ti -1c
.RI "\fBconf\&.language\fP = None"
.br
.ti -1c
.RI "list \fBconf\&.exclude_patterns\fP = ['_build', 'Thumbs\&.db', '\&.DS_Store']"
.br
.ti -1c
.RI "string \fBconf\&.pygments_style\fP = 'sphinx'"
.br
.ti -1c
.RI "bool \fBconf\&.todo_include_todos\fP = False"
.br
.ti -1c
.RI "string \fBconf\&.html_theme\fP = 'alabaster'"
.br
.ti -1c
.RI "list \fBconf\&.html_static_path\fP = []"
.br
.ti -1c
.RI "dictionary \fBconf\&.html_sidebars\fP"
.br
.ti -1c
.RI "string \fBconf\&.htmlhelp_basename\fP = 'c\-template\-REPLACEME\-doc'"
.br
.ti -1c
.RI "dictionary \fBconf\&.latex_elements\fP"
.br
.ti -1c
.RI "list \fBconf\&.latex_documents\fP"
.br
.ti -1c
.RI "list \fBconf\&.man_pages\fP = [(master_doc, 'c\-template\-REPLACEME', 'c\-template\-REPLACEME Documentation', [author], 1)]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
