.TH "conn_handle_data" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
conn_handle_data \- struct containing arguments passed into pthread  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBsocket_server_t\fP * \fBsrv\fP"
.br
.ti -1c
.RI "\fBclient_conn_t\fP * \fBconn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct containing arguments passed into pthread 
.PP
Definition at line 96 of file socket_server\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBclient_conn_t\fP* conn_handle_data::conn"

.PP
Definition at line 98 of file socket_server\&.h\&.
.SS "\fBsocket_server_t\fP* conn_handle_data::srv"

.PP
Definition at line 97 of file socket_server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
