.TH "ConversionStatus" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConversionStatus
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCborTag\fP \fBlastTag\fP"
.br
.ti -1c
.RI "uint64_t \fBoriginalNumber\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 164 of file cbortojson\&.c\&.
.SH "Field Documentation"
.PP 
.SS "int ConversionStatus::flags"

.PP
Definition at line 167 of file cbortojson\&.c\&.
.SS "\fBCborTag\fP ConversionStatus::lastTag"

.PP
Definition at line 165 of file cbortojson\&.c\&.
.SS "uint64_t ConversionStatus::originalNumber"

.PP
Definition at line 166 of file cbortojson\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
