.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/crypto_test.c" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/crypto_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'crypto/sha512\&.h'\fP
.br
\fC#include 'crypto/sha256\&.h'\fP
.br
\fC#include 'crypto/sha1\&.h'\fP
.br
\fC#include 'crypto/ecdsa\&.h'\fP
.br
\fC#include 'encoding/base64\&.h'\fP
.br
\fC#include 'mbedtls/base64\&.h'\fP
.br
\fC#include 'crypto/peerutils\&.h'\fP
.br
\fC#include 'crypto/key\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_libp2p_crypto_ecdsa_private_key_save\fP (void **stat)"
.br
.ti -1c
.RI "void \fBtest_libp2p_crypto_ecdsa_keypair_generation\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_libp2p_crypto_hashing_sha1_hmac\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_libp2p_crypto_hashing_sha256_hmac\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_libp2p_crypto_hashing_sha512\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_libp2p_crypto_hashing_sha256\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_libp2p_crypto_cbor_encode_pub_key\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 389 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_cbor_encode_pub_key (void ** state)"

.PP
Definition at line 306 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_ecdsa_keypair_generation (void ** state)"

.PP
Definition at line 52 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_ecdsa_private_key_save (void ** stat)"

.PP
Definition at line 20 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_hashing_sha1_hmac (void ** state)"

.PP
Definition at line 85 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_hashing_sha256 (void ** state)"

.PP
Definition at line 255 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_hashing_sha256_hmac (void ** state)"

.PP
Definition at line 144 of file crypto_test\&.c\&.
.SS "void test_libp2p_crypto_hashing_sha512 (void ** state)"

.PP
Definition at line 203 of file crypto_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
