.TH "EphemeralPublicKey" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EphemeralPublicKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ephemeral\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBnum_bits\fP"
.br
.ti -1c
.RI "uint64_t \fBx\fP"
.br
.ti -1c
.RI "uint64_t \fBy\fP"
.br
.ti -1c
.RI "unsigned char * \fBbytes\fP"
.br
.ti -1c
.RI "size_t \fBbytes_size\fP"
.br
.ti -1c
.RI "unsigned char * \fBshared_key\fP"
.br
.ti -1c
.RI "size_t \fBshared_key_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file ephemeral\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* EphemeralPublicKey::bytes"

.PP
Definition at line 23 of file ephemeral\&.h\&.
.SS "size_t EphemeralPublicKey::bytes_size"

.PP
Definition at line 24 of file ephemeral\&.h\&.
.SS "size_t EphemeralPublicKey::num_bits"

.PP
Definition at line 20 of file ephemeral\&.h\&.
.SS "unsigned char* EphemeralPublicKey::shared_key"

.PP
Definition at line 25 of file ephemeral\&.h\&.
.SS "size_t EphemeralPublicKey::shared_key_size"

.PP
Definition at line 26 of file ephemeral\&.h\&.
.SS "uint64_t EphemeralPublicKey::x"

.PP
Definition at line 21 of file ephemeral\&.h\&.
.SS "uint64_t EphemeralPublicKey::y"

.PP
Definition at line 22 of file ephemeral\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
