.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multihash/errors.c" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multihash/errors.c
.SH SYNOPSIS
.br
.PP
\fC#include 'multihash/errors\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBmh_error_string\fP (int code)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const char* mh_error_string (int code)"
Convert an error code into a string 
.PP
\fBParameters\fP
.RS 4
\fIcode\fP the error code 
.RE
.PP
\fBReturns\fP
.RS 4
the error as text 
.RE
.PP

.PP
Definition at line 8 of file errors\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
