.TH "file_logger" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBthread_logger\fP * \fBthl\fP"
.br
.ti -1c
.RI "int \fBfile_descriptor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file logger\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int file_logger::file_descriptor"

.PP
Definition at line 89 of file logger\&.h\&.
.SS "\fBthread_logger\fP * file_logger::thl"

.PP
Definition at line 88 of file logger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
