.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multihash/generic.h" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multihash/generic.h \- generic definitions for multihashes  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmh_assert_static\fP(isTrue)   void mh_assert_static(char x[1 \- (!(isTrue))])"
.br
.ti -1c
.RI "#define \fBUNUSED\fP(x)   (void)(x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
generic definitions for multihashes 


.PP
Definition in file \fBgeneric\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define mh_assert_static(isTrue)   void mh_assert_static(char x[1 \- (!(isTrue))])"

.PP
Definition at line 7 of file generic\&.h\&.
.SS "#define UNUSED(x)   (void)(x)"

.PP
Definition at line 9 of file generic\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
