.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multihash/hex.h" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/multihash/hex.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhex_to_bin\fP (unsigned const char *hex, unsigned char *dest)"
.br
.ti -1c
.RI "void \fBbin_to_hex\fP (unsigned const char *bin, unsigned char *dest)"
.br
.ti -1c
.RI "void \fBdec_to_hex\fP (const unsigned long long *dec, unsigned char *dest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void bin_to_hex (unsigned const char * bin, unsigned char * dest)"

.SS "void dec_to_hex (const unsigned long long * dec, unsigned char * dest)"

.SS "void hex_to_bin (unsigned const char * hex, unsigned char * dest)"

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
