.TH "job" 3 "Tue Jul 21 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
job
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBjob\fP * \fBprev\fP"
.br
.ti -1c
.RI "void(* \fBfunction\fP )(void *\fBarg\fP)"
.br
.ti -1c
.RI "void * \fBarg\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file thread_pool\&.c\&.
.SH "Field Documentation"
.PP 
.SS "void* job::arg"

.PP
Definition at line 58 of file thread_pool\&.c\&.
.SS "void(* job::function) (void *\fBarg\fP)"

.PP
Definition at line 57 of file thread_pool\&.c\&.
.SS "struct \fBjob\fP* job::prev"

.PP
Definition at line 56 of file thread_pool\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
