.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/key.c" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/key.c \- public/private key management functions  

.SH SYNOPSIS
.br
.PP
\fC#include 'crypto/key\&.h'\fP
.br
\fC#include 'crypto/peerutils\&.h'\fP
.br
\fC#include 'crypto/sha256\&.h'\fP
.br
\fC#include 'protobuf/protobuf\&.h'\fP
.br
\fC#include 'tinycbor/cbor\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBpublic_key_t\fP * \fBlibp2p_crypto_public_key_new\fP (void)"
.br
.RI "returns a new instance of public_key_t "
.ti -1c
.RI "void \fBlibp2p_crypto_public_key_free\fP (\fBpublic_key_t\fP *in)"
.br
.RI "free up resources associated with a public_key_t instance "
.ti -1c
.RI "\fBprivate_key_t\fP * \fBlibp2p_crypto_private_key_new\fP (void)"
.br
.RI "returns a new instance of private_key_t "
.ti -1c
.RI "void \fBlibp2p_crypto_private_key_free\fP (\fBprivate_key_t\fP *in)"
.br
.RI "frees up resources associated with a private_key_t instance "
.ti -1c
.RI "int \fBlibp2p_crypto_private_key_copy\fP (const \fBprivate_key_t\fP *source, \fBprivate_key_t\fP *destination)"
.br
.RI "copies a private key "
.ti -1c
.RI "\fBpublic_key_t\fP * \fBlibp2p_crypto_public_key_cbor_decode\fP (\fBcbor_encoded_data_t\fP *data)"
.br
.RI "used to cbor data a chunk of data "
.ti -1c
.RI "\fBcbor_encoded_data_t\fP * \fBlibp2p_crypto_public_key_cbor_encode\fP (\fBpublic_key_t\fP *pub_key, size_t *bytes_written)"
.br
.RI "used to cbor encode a public_key_t type for sending over the wire "
.in -1c
.SH "Detailed Description"
.PP 
public/private key management functions 

provides tooling for working with public/private keys and transmitting them over the wire 
.PP
\fBWarning\fP
.RS 4
none of these functions and structures are thread safe 
.RE
.PP

.PP
Definition in file \fBkey\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int libp2p_crypto_private_key_copy (const \fBprivate_key_t\fP * source, \fBprivate_key_t\fP * destination)"

.PP
copies a private key 
.PP
\fBParameters\fP
.RS 4
\fIsource\fP the key we are copying 
.br
\fIdestination\fP the location to copy to 
.RE
.PP
\fBReturns\fP
.RS 4
Success: 0 
.PP
Failure: 1 
.RE
.PP
\fBNote\fP
.RS 4
does not allocate memory for caller 
.RE
.PP

.PP
Definition at line 88 of file key\&.c\&.
.SS "void libp2p_crypto_private_key_free (\fBprivate_key_t\fP * in)"

.PP
frees up resources associated with a private_key_t instance 
.PP
Definition at line 71 of file key\&.c\&.
.SS "\fBprivate_key_t\fP* libp2p_crypto_private_key_new (void)"

.PP
returns a new instance of private_key_t 
.PP
\fBReturns\fP
.RS 4
Success: pointer to an instance of private_key_t 
.PP
Failure: NULL pointer 
.RE
.PP

.PP
Definition at line 58 of file key\&.c\&.
.SS "\fBpublic_key_t\fP* libp2p_crypto_public_key_cbor_decode (\fBcbor_encoded_data_t\fP * data)"

.PP
used to cbor data a chunk of data 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP an instance of cbor_encoded_data_t created with libp2p_crypto_public_key_cbor_encode 
.RE
.PP
\fBReturns\fP
.RS 4
Success: pointer to a public_key_t instance 
.PP
Failure: NULL pointer 
.RE
.PP

.PP
Definition at line 110 of file key\&.c\&.
.SS "\fBcbor_encoded_data_t\fP* libp2p_crypto_public_key_cbor_encode (\fBpublic_key_t\fP * pub_key, size_t * bytes_written)"

.PP
used to cbor encode a public_key_t type for sending over the wire 
.PP
\fBParameters\fP
.RS 4
\fIpub_key\fP an instance of public_key_t fully filled out 
.br
\fIbytes_written\fP returns the number of bytes written 
.RE
.PP
\fBReturns\fP
.RS 4
Success: pointer to an instance of cbor_encoded_data_t 
.PP
Failure: NULL pointer 
.RE
.PP

.PP
\fBTodo\fP
.RS 4
figure out why this returns an error 
.RE
.PP

.PP
Definition at line 219 of file key\&.c\&.
.SS "void libp2p_crypto_public_key_free (\fBpublic_key_t\fP * in)"

.PP
free up resources associated with a public_key_t instance 
.PP
Definition at line 48 of file key\&.c\&.
.SS "\fBpublic_key_t\fP* libp2p_crypto_public_key_new (void)"

.PP
returns a new instance of public_key_t the size of the key data
.PP
\fBReturns\fP
.RS 4
Success: pointer to an instance of public_key_t 
.PP
Failure: NULL pointer 
.RE
.PP

.PP
Definition at line 35 of file key\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
