.TH "KnownTagData" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KnownTagData
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBtag\fP"
.br
.ti -1c
.RI "uint32_t \fBtypes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 267 of file cborvalidation\&.c\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t KnownTagData::tag"

.PP
Definition at line 268 of file cborvalidation\&.c\&.
.SS "uint32_t KnownTagData::types"

.PP
Definition at line 269 of file cborvalidation\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
