.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/protobuf/main.c" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/protobuf/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include 'protobuf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBos_utils_file_size\fP (const char *path)"
.br
.ti -1c
.RI "char * \fBgetWireType\fP (enum \fBWireType\fP type)"
.br
.ti -1c
.RI "void \fBstripit\fP (int argc, char **argv)"
.br
.ti -1c
.RI "void \fBstrip_quotes\fP (int argc, char **argv)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* getWireType (enum \fBWireType\fP type)"

.PP
Definition at line 25 of file main\&.c\&.
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 59 of file main\&.c\&.
.SS "size_t os_utils_file_size (const char * path)"
opens a file to give a list of fields 
.PP
Definition at line 12 of file main\&.c\&.
.SS "void strip_quotes (int argc, char ** argv)"

.PP
Definition at line 51 of file main\&.c\&.
.SS "void stripit (int argc, char ** argv)"

.PP
Definition at line 43 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
