.TH "map_int_t" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_int_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmap_base_t\fP \fBbase\fP"
.br
.ti -1c
.RI "int * \fBref\fP"
.br
.ti -1c
.RI "int \fBtmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file map\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBmap_base_t\fP map_int_t::base"

.PP
Definition at line 59 of file map\&.h\&.
.SS "int* map_int_t::ref"

.PP
Definition at line 59 of file map\&.h\&.
.SS "int map_int_t::tmp"

.PP
Definition at line 59 of file map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
