.TH "map_char_t" 3 "Tue Jul 21 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_char_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBmap_base_t\fP \fBbase\fP"
.br
.ti -1c
.RI "char * \fBref\fP"
.br
.ti -1c
.RI "char \fBtmp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file map\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBmap_base_t\fP map_char_t::base"

.PP
Definition at line 60 of file map\&.h\&.
.SS "char* map_char_t::ref"

.PP
Definition at line 60 of file map\&.h\&.
.SS "char map_char_t::tmp"

.PP
Definition at line 60 of file map\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
