.TH "map_node_t" 3 "Tue Jul 21 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
map_node_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBhash\fP"
.br
.ti -1c
.RI "void * \fBvalue\fP"
.br
.ti -1c
.RI "\fBmap_node_t\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Copyright (c) 2014 rxi
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the MIT license\&. See LICENSE for details\&. 
.PP
Definition at line 12 of file map\&.c\&.
.SH "Field Documentation"
.PP 
.SS "unsigned map_node_t::hash"

.PP
Definition at line 13 of file map\&.c\&.
.SS "\fBmap_node_t\fP* map_node_t::next"

.PP
Definition at line 15 of file map\&.c\&.
.SS "void* map_node_t::value"

.PP
Definition at line 14 of file map\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
