.TH "md__media_solidity__d_a_t_a__code__r_trade_ltd_libcp2p_src_multiaddr__s_t_a_t_u_s" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__media_solidity__d_a_t_a__code__r_trade_ltd_libcp2p_src_multiaddr__s_t_a_t_u_s \- STATUS: 

.IP "\(bu" 2
Compatibility: Windows/Mac/Linux/Openbsd based systems (probably more)
.IP "\(bu" 2
Finished Base58\&.h Encryption/Decryption Algorhytm
.IP "\(bu" 2
Finished \fBEndian\&.h\fP Library for automating compiling for Linux/Mac/Windows
.IP "\(bu" 2
Finished Varhexutils - Different conversion algorhytms between bytes and strings etc\&.
.IP "\(bu" 2
Finsihed Varint\&.h - Conversion from Hex
.IP "\(bu" 2
Finished \fBProtocols\&.h\fP - Library for loading protocols & manipulating them easily\&.
.IP "\(bu" 2
Finished: \fBMultiaddr\&.h\fP (easy library for developers)
.IP "\(bu" 2
Finished: \fBProtoutils\&.h\fP Converting from string to hex/binary, analizing strings/bin for validity,parsing ipv4,etc\&.
.IP "\(bu" 2
Finished: Readme - Documentation on how to use everything so any new developer can easily use all of this 
.PP
.SH "Secondary things that might need to be implemented:"
.PP
.IP "\(bu" 2
Protocols, everything except IP4,TCP,UDP,IPFS - These we actually need\&.
.IP "\(bu" 2
Few issues that are not urgent:
.IP "  \(bu" 4
Decapsulation of tunneled protocols doesn't work, this will be fixed if needed in \fBmultiaddr\&.h\fP/m_decapsulate
.IP "  \(bu" 4
Endianness Check - \fBprotoutils\&.h\fP/in protocols UDP,TCP 
.PP

.PP

