.TH "message" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
message
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messages\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBMESSAGE_TYPES_T\fP \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBlen\fP"
.br
.RI "the type of message "
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.RI "the size of the data contained in the message "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file messages\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* message::data"

.PP
the size of the data contained in the message 
.PP
Definition at line 93 of file messages\&.h\&.
.SS "size_t message::len"

.PP
the type of message 
.PP
Definition at line 92 of file messages\&.h\&.
.SS "\fBMESSAGE_TYPES_T\fP message::type"

.PP
Definition at line 91 of file messages\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
