.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multibase/multibase_test.c" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multibase/multibase_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'multibase/multibase\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_multibase_encode_decode_base16\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multibase_encode_decode_base32\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multibase_encode_decode_base64\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 158 of file multibase_test\&.c\&.
.SS "void test_multibase_encode_decode_base16 (void ** state)"

.PP
Definition at line 13 of file multibase_test\&.c\&.
.SS "void test_multibase_encode_decode_base32 (void ** state)"

.PP
Definition at line 59 of file multibase_test\&.c\&.
.SS "void test_multibase_encode_decode_base64 (void ** state)"

.PP
Definition at line 108 of file multibase_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
