.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multicodec/multicodec_test.c" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multicodec/multicodec_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include 'multicodec/codecs\&.h'\fP
.br
\fC#include 'multicodec/multicodec\&.h'\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_valide_codecs\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multicodec_encode_decode\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 89 of file multicodec_test\&.c\&.
.SS "void test_multicodec_encode_decode (void ** state)"

.PP
Definition at line 36 of file multicodec_test\&.c\&.
.SS "void test_valide_codecs (void ** state)"

.PP
Definition at line 26 of file multicodec_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
