.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multiaddr/multiaddr_test.c" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multiaddr/multiaddr_test.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <setjmp\&.h>\fP
.br
\fC#include <cmocka\&.h>\fP
.br
\fC#include 'multiaddr/multiaddr\&.h'\fP
.br
\fC#include 'utils/varhexutils\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBassert__\fP(x)   for ( ; !(x) ; assert(x) )"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBtest_int_to_hex\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_hex_to_var\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_new_from_string\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_new_like_libp2p\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multiaddr_utils\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multiaddr_get_peer_id\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multiaddr_peer_id\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_multiaddr_bytes\fP (void **state)"
.br
.ti -1c
.RI "void \fBtest_full\fP (void **state)"
.br
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define assert__(x)   for ( ; !(x) ; assert(x) )"

.PP
Definition at line 10 of file multiaddr_test\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (void)"

.PP
Definition at line 222 of file multiaddr_test\&.c\&.
.SS "void test_full (void ** state)"

.PP
Definition at line 180 of file multiaddr_test\&.c\&.
.SS "void test_hex_to_var (void ** state)"

.PP
Definition at line 22 of file multiaddr_test\&.c\&.
.SS "void test_int_to_hex (void ** state)"

.PP
Definition at line 13 of file multiaddr_test\&.c\&.
.SS "void test_multiaddr_bytes (void ** state)"

.PP
Definition at line 162 of file multiaddr_test\&.c\&.
.SS "void test_multiaddr_get_peer_id (void ** state)"

.PP
Definition at line 83 of file multiaddr_test\&.c\&.
.SS "void test_multiaddr_peer_id (void ** state)"

.PP
Definition at line 103 of file multiaddr_test\&.c\&.
.SS "void test_multiaddr_utils (void ** state)"

.PP
Definition at line 65 of file multiaddr_test\&.c\&.
.SS "void test_new_from_string (void ** state)"

.PP
Definition at line 32 of file multiaddr_test\&.c\&.
.SS "void test_new_like_libp2p (void ** state)"

.PP
Definition at line 46 of file multiaddr_test\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
