.TH "multicodec_encoded" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multicodec_encoded
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multicodec\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBcodec\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.RI "the codec used for encoding "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file multicodec\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* multicodec_encoded::codec"

.PP
Definition at line 36 of file multicodec\&.h\&.
.SS "char* multicodec_encoded::data"

.PP
the codec used for encoding 
.PP
Definition at line 37 of file multicodec\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
