.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multihash/operations.c" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/multihash/operations.c
.SH SYNOPSIS
.br
.PP
\fC#include <multihash/operations\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxor_bin\fP (const unsigned char *bin1, const unsigned char *bin2, unsigned char *dest)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void xor_bin (const unsigned char * bin1, const unsigned char * bin2, unsigned char * dest)"

.PP
Definition at line 8 of file operations\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
