.TH "peer_id" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peer_id
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <peerutils\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.RI "the actual \fBpeer_id\fP data "
.ti -1c
.RI "size_t \fBlen\fP"
.br
.RI "the size of the data member "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file peerutils\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* peer_id::data"

.PP
the actual \fBpeer_id\fP data 
.PP
Definition at line 22 of file peerutils\&.h\&.
.SS "size_t peer_id::len"

.PP
the size of the data member 
.PP
Definition at line 24 of file peerutils\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
