.TH "private_key" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
private_key
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <key\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBkey_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.RI "the type of the key "
.ti -1c
.RI "size_t \fBdata_size\fP"
.br
.RI "the key data in PEM format "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file key\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* private_key::data"

.PP
the type of the key 
.PP
Definition at line 51 of file key\&.h\&.
.SS "size_t private_key::data_size"

.PP
the key data in PEM format 
.PP
Definition at line 52 of file key\&.h\&.
.SS "\fBkey_type_t\fP private_key::type"

.PP
Definition at line 50 of file key\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
