.TH "Protocol" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Protocol
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <protocols\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdeccode\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "char \fBname\fP [30]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file protocols\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int Protocol::deccode"

.PP
Definition at line 17 of file protocols\&.h\&.
.SS "char Protocol::name[30]"

.PP
Definition at line 19 of file protocols\&.h\&.
.SS "int Protocol::size"

.PP
Definition at line 18 of file protocols\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
