.TH "PublicKey" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PublicKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <key\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBKeyType\fP \fBtype\fP"
.br
.ti -1c
.RI "unsigned char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBdata_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file key\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* PublicKey::data"

.PP
Definition at line 13 of file key\&.h\&.
.SS "size_t PublicKey::data_size"

.PP
Definition at line 14 of file key\&.h\&.
.SS "enum \fBKeyType\fP PublicKey::type"

.PP
Definition at line 12 of file key\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
