.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/sha1.c" 3 "Fri Jul 24 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/sha1.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mbedtls/sha1\&.h'\fP
.br
\fC#include 'crypto/sha1\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBlibp2p_crypto_hashing_sha1\fP (const unsigned char *input, size_t input_length, unsigned char *output)"
.br
.ti -1c
.RI "int \fBlibp2p_crypto_hashing_sha1_init\fP (mbedtls_sha1_context *ctx)"
.br
.RI "Initialize a sha1 hmac process\&. "
.ti -1c
.RI "int \fBlibp2p_crypto_hashing_sha1_update\fP (mbedtls_sha1_context *ctx, const unsigned char *input, size_t input_size)"
.br
.RI "Update a sha1 hmac process\&. "
.ti -1c
.RI "int \fBlibp2p_crypto_hashing_sha1_finish\fP (mbedtls_sha1_context *ctx, unsigned char *hash)"
.br
.RI "finalize a sha1 hmac process "
.ti -1c
.RI "int \fBlibp2p_crypto_hashing_sha1_free\fP (mbedtls_sha1_context *ctx)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int libp2p_crypto_hashing_sha1 (const unsigned char * input, size_t input_length, unsigned char * output)"

.PP
Definition at line 25 of file sha1\&.c\&.
.SS "int libp2p_crypto_hashing_sha1_finish (mbedtls_sha1_context * ctx, unsigned char * hash)"

.PP
finalize a sha1 hmac process finalize a sha1 hmac process 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP the context 
.br
\fIhash\fP where to put the results (for sha1, should be 20 bytes long) 
.RE
.PP
\fBReturns\fP
.RS 4
true(1) on success, otherwise false(0) 
.RE
.PP

.PP
Definition at line 64 of file sha1\&.c\&.
.SS "int libp2p_crypto_hashing_sha1_free (mbedtls_sha1_context * ctx)"
Clean up allocated memory 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP the context 
.RE
.PP
\fBReturns\fP
.RS 4
true(1) on success, otherwise false(0) 
.RE
.PP

.PP
Definition at line 75 of file sha1\&.c\&.
.SS "int libp2p_crypto_hashing_sha1_init (mbedtls_sha1_context * ctx)"

.PP
Initialize a sha1 hmac process\&. Initialize a sha1 hmac process 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP the context 
.RE
.PP
\fBReturns\fP
.RS 4
true(1) on success, otherwise false(0) 
.RE
.PP

.PP
Definition at line 39 of file sha1\&.c\&.
.SS "int libp2p_crypto_hashing_sha1_update (mbedtls_sha1_context * ctx, const unsigned char * input, size_t input_size)"

.PP
Update a sha1 hmac process\&. Update a sha1 hmac process 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP the context 
.br
\fIinput\fP the data to add 
.br
\fIinput_size\fP the size of input 
.RE
.PP
\fBReturns\fP
.RS 4
true(1) on success, otherwise false(0) 
.RE
.PP

.PP
Definition at line 51 of file sha1\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
