.TH "sockaddr" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr \- alias for \fCstruct sockaddr\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SH "Detailed Description"
.PP 
alias for \fCstruct sockaddr\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
