.TH "sockaddr_storage" 3 "Thu Jul 23 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr_storage \- alias for \fCstruct \fBsockaddr_storage\fP\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SH "Detailed Description"
.PP 
alias for \fCstruct \fBsockaddr_storage\fP\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
