.TH "socket_client" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket_client
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket_client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket_number\fP"
.br
.ti -1c
.RI "\fBaddr_info\fP * \fBpeer_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a generic tcp/udp socket client 
.PP
Definition at line 34 of file socket_client\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBaddr_info\fP* socket_client::peer_address"

.PP
Definition at line 36 of file socket_client\&.h\&.
.SS "int socket_client::socket_number"

.PP
Definition at line 35 of file socket_client\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
