.TH "socket_server_config" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket_server_config
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket_server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBthreadpool_task_func\fP * \fBfn_tcp\fP"
.br
.RI "the thread pool task function to use for processing tcp connections "
.ti -1c
.RI "\fBthreadpool_task_func\fP * \fBfn_udp\fP"
.br
.RI "the thread pool task function to use for processing tcp connections "
.ti -1c
.RI "int \fBmax_connections\fP"
.br
.ti -1c
.RI "int \fBnum_threads\fP"
.br
.ti -1c
.RI "int \fBnum_addrs\fP"
.br
.ti -1c
.RI "\fBmulti_addr_t\fP ** \fBaddrs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file socket_server\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBmulti_addr_t\fP** socket_server_config::addrs"

.PP
Definition at line 53 of file socket_server\&.h\&.
.SS "\fBthreadpool_task_func\fP* socket_server_config::fn_tcp"

.PP
the thread pool task function to use for processing tcp connections 
.PP
Definition at line 47 of file socket_server\&.h\&.
.SS "\fBthreadpool_task_func\fP* socket_server_config::fn_udp"

.PP
the thread pool task function to use for processing tcp connections 
.PP
Definition at line 49 of file socket_server\&.h\&.
.SS "int socket_server_config::max_connections"

.PP
Definition at line 50 of file socket_server\&.h\&.
.SS "int socket_server_config::num_addrs"

.PP
Definition at line 52 of file socket_server\&.h\&.
.SS "int socket_server_config::num_threads"

.PP
Definition at line 51 of file socket_server\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
