.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/network/socket_client.h" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/network/socket_client.h \- stuff related to socket clients (ie, connecting to socket servers)  

.SH SYNOPSIS
.br
.PP
\fC#include 'multiaddr/multiaddr\&.h'\fP
.br
\fC#include 'socket\&.h'\fP
.br
\fC#include 'thirdparty/logger/logger\&.h'\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsocket_client\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBsocket_client\fP \fBsocket_client_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsocket_client_t\fP * \fBnew_socket_client\fP (\fBthread_logger\fP *thl, \fBmulti_addr_t\fP *addr)"
.br
.RI "returns a new socket client connected to \fCaddr:port\fP "
.in -1c
.SH "Detailed Description"
.PP 
stuff related to socket clients (ie, connecting to socket servers) 


.PP
Definition in file \fBsocket_client\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBsocket_client\fP \fBsocket_client_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBsocket_client_t\fP* new_socket_client (\fBthread_logger\fP * thl, \fBmulti_addr_t\fP * addr)"

.PP
returns a new socket client connected to \fCaddr:port\fP 
.PP
\fBParameters\fP
.RS 4
\fIthl\fP an instance of a thread logger 
.br
\fIaddr\fP the multiaddr to connect to 
.RE
.PP

.PP
Definition at line 40 of file socket_client\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
