.TH "sockaddr_storage" 3 "Tue Jul 21 2020" "c-template" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sockaddr_storage \- alias for \fCstruct \fBsockaddr_storage\fP\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket\&.h>\fP
.SH "Detailed Description"
.PP 
alias for \fCstruct \fBsockaddr_storage\fP\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for c-template from the source code\&.
