.TH "socket_client" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
socket_client
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <socket_client\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsocket_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
a generic tcp/udp socket client 
.PP
Definition at line 21 of file socket_client\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int socket_client::socket_number"

.PP
Definition at line 22 of file socket_client\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
