.TH "StretchedKey" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StretchedKey
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ephemeral\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char * \fBiv\fP"
.br
.ti -1c
.RI "size_t \fBiv_size\fP"
.br
.ti -1c
.RI "unsigned char * \fBcipher_key\fP"
.br
.ti -1c
.RI "size_t \fBcipher_size\fP"
.br
.ti -1c
.RI "unsigned char * \fBmac_key\fP"
.br
.ti -1c
.RI "size_t \fBmac_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General helpers for ephemeral keys 
.PP
Definition at line 10 of file ephemeral\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char* StretchedKey::cipher_key"

.PP
Definition at line 13 of file ephemeral\&.h\&.
.SS "size_t StretchedKey::cipher_size"

.PP
Definition at line 14 of file ephemeral\&.h\&.
.SS "unsigned char* StretchedKey::iv"

.PP
Definition at line 11 of file ephemeral\&.h\&.
.SS "size_t StretchedKey::iv_size"

.PP
Definition at line 12 of file ephemeral\&.h\&.
.SS "unsigned char* StretchedKey::mac_key"

.PP
Definition at line 15 of file ephemeral\&.h\&.
.SS "size_t StretchedKey::mac_size"

.PP
Definition at line 16 of file ephemeral\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
