.TH "Test3" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Test3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Test3_protobuf\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBa_string\fP"
.br
.ti -1c
.RI "int \fBan_int\fP"
.br
.ti -1c
.RI "struct \fBTest2\fP * \fBtest2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file Test3_protobuf\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* Test3::a_string"

.PP
Definition at line 11 of file Test3_protobuf\&.h\&.
.SS "int Test3::an_int"

.PP
Definition at line 12 of file Test3_protobuf\&.h\&.
.SS "struct \fBTest2\fP* Test3::test2"

.PP
Definition at line 13 of file Test3_protobuf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
