.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/protobuf/test/test_protobuf.h" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/protobuf/test/test_protobuf.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'Test1_protobuf\&.h'\fP
.br
\fC#include 'Test2_protobuf\&.h'\fP
.br
\fC#include 'Test3_protobuf\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBtest_complex_protobuf\fP ()"
.br
.ti -1c
.RI "int \fBtest_rightshift\fP ()"
.br
.ti -1c
.RI "int \fBtest_write_simple\fP ()"
.br
.ti -1c
.RI "int \fBtest_write_negative\fP ()"
.br
.ti -1c
.RI "int \fBtest_write_string\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int test_complex_protobuf ()"

.PP
Definition at line 29 of file test_protobuf\&.h\&.
.SS "int test_rightshift ()"

.PP
Definition at line 84 of file test_protobuf\&.h\&.
.SS "int test_write_negative ()"

.PP
Definition at line 171 of file test_protobuf\&.h\&.
.SS "int test_write_simple ()"

.PP
Definition at line 124 of file test_protobuf\&.h\&.
.SS "int test_write_string ()"

.PP
Definition at line 217 of file test_protobuf\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
