.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/protobuf/test/Test3_protobuf.h" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/protobuf/test/Test3_protobuf.h
.SH SYNOPSIS
.br
.PP
\fC#include 'Test2_protobuf\&.h'\fP
.br
\fC#include 'protobuf\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTest3\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBTest3_new\fP (struct \fBTest3\fP **test1)"
.br
.ti -1c
.RI "int \fBTest3_free\fP (struct \fBTest3\fP *test1)"
.br
.ti -1c
.RI "int \fBTest3_protobuf_encode\fP (struct \fBTest3\fP *incoming, unsigned char *buffer, size_t max_buffer_length, size_t *bytes_written)"
.br
.ti -1c
.RI "int \fBTest3_protobuf_decode\fP (unsigned char *buffer, size_t buffer_length, struct \fBTest3\fP **\fBoutput\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int Test3_free (struct \fBTest3\fP * test1)"

.PP
Definition at line 23 of file Test3_protobuf\&.c\&.
.SS "int Test3_new (struct \fBTest3\fP ** test1)"

.PP
Definition at line 13 of file Test3_protobuf\&.c\&.
.SS "int Test3_protobuf_decode (unsigned char * buffer, size_t buffer_length, struct \fBTest3\fP ** output)"

.PP
Definition at line 58 of file Test3_protobuf\&.c\&.
.SS "int Test3_protobuf_encode (struct \fBTest3\fP * incoming, unsigned char * buffer, size_t max_buffer_length, size_t * bytes_written)"

.PP
Definition at line 32 of file Test3_protobuf\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
