.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/testutils/testutils.h" 3 "Sat Aug 8 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/testutils/testutils.h
.SH SYNOPSIS
.br
.PP
\fC#include 'crypto/ecdsa\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBecdsa_private_key_t\fP * \fBnew_ecdsa_private_key\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBecdsa_private_key_t\fP* new_ecdsa_private_key (void)"

.PP
Definition at line 7 of file testutils\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
