.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/testutils/testutils.c" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/testutils/testutils.c
.SH SYNOPSIS
.br
.PP
\fC#include 'testutils/testutils\&.h'\fP
.br
\fC#include 'crypto/ecdsa\&.h'\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <mbedtls/ecp\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBecdsa_private_key_t\fP * \fBnew_ecdsa_private_key\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBecdsa_private_key_t\fP* new_ecdsa_private_key (void)"

.PP
Definition at line 7 of file testutils\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
