.TH "thpool_" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thpool_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBthread\fP ** \fBthreads\fP"
.br
.ti -1c
.RI "volatile int \fBnum_threads_alive\fP"
.br
.ti -1c
.RI "volatile int \fBnum_threads_working\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBthcount_lock\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBthreads_all_idle\fP"
.br
.ti -1c
.RI "\fBjobqueue\fP \fBjobqueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExamples\fP
.in +1c
\fB/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/thirdparty/thread_pool/thread_pool\&.h\fP, and \fB/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/utils/thread_pool\&.h\fP\&.
.PP
Definition at line 78 of file thread_pool\&.c\&.
.SH "Field Documentation"
.PP 
.SS "\fBjobqueue\fP thpool_::jobqueue"

.PP
Definition at line 84 of file thread_pool\&.c\&.
.SS "volatile int thpool_::num_threads_alive"

.PP
Definition at line 80 of file thread_pool\&.c\&.
.SS "volatile int thpool_::num_threads_working"

.PP
Definition at line 81 of file thread_pool\&.c\&.
.SS "pthread_mutex_t thpool_::thcount_lock"

.PP
Definition at line 82 of file thread_pool\&.c\&.
.SS "\fBthread\fP** thpool_::threads"

.PP
Definition at line 79 of file thread_pool\&.c\&.
.SS "pthread_cond_t thpool_::threads_all_idle"

.PP
Definition at line 83 of file thread_pool\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
