.TH "thread_logger" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thread_logger
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logger\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBdebug\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "\fBmutex_fn\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBmutex_fn\fP \fBunlock\fP"
.br
.ti -1c
.RI "\fBlog_fn\fP \fBlog\fP"
.br
.ti -1c
.RI "\fBlog_fnf\fP \fBlogf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 72 of file logger\&.h\&.
.SH "Field Documentation"
.PP 
.SS "bool thread_logger::debug"

.PP
Definition at line 74 of file logger\&.h\&.
.SS "\fBmutex_fn\fP thread_logger::lock"

.PP
Definition at line 76 of file logger\&.h\&.
.SS "\fBlog_fn\fP thread_logger::log"

.PP
Definition at line 78 of file logger\&.h\&.
.SS "\fBlog_fnf\fP thread_logger::logf"

.PP
Definition at line 79 of file logger\&.h\&.
.SS "pthread_mutex_t thread_logger::mutex"

.PP
Definition at line 75 of file logger\&.h\&.
.SS "\fBmutex_fn\fP thread_logger::unlock"

.PP
Definition at line 77 of file logger\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
