.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/tinycbor/tinycbor-version.h" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/tinycbor/tinycbor-version.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTINYCBOR_VERSION_MAJOR\fP   0"
.br
.ti -1c
.RI "#define \fBTINYCBOR_VERSION_MINOR\fP   5"
.br
.ti -1c
.RI "#define \fBTINYCBOR_VERSION_PATCH\fP   4"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define TINYCBOR_VERSION_MAJOR   0"

.PP
Definition at line 1 of file tinycbor\-version\&.h\&.
.SS "#define TINYCBOR_VERSION_MINOR   5"

.PP
Definition at line 2 of file tinycbor\-version\&.h\&.
.SS "#define TINYCBOR_VERSION_PATCH   4"

.PP
Definition at line 3 of file tinycbor\-version\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
