.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/tinycbor/utf8_p.h" 3 "Thu Aug 6 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/tinycbor/utf8_p.h
.SH SYNOPSIS
.br
.PP
\fC#include 'tinycbor/compilersupport_p\&.h'\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static uint32_t \fBget_utf8\fP (const uint8_t **buffer, const uint8_t *\fBend\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static uint32_t get_utf8 (const uint8_t ** buffer, const uint8_t * end)\fC [inline]\fP, \fC [static]\fP"

.PP
Definition at line 32 of file utf8_p\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
