.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/crypto/util.h" 3 "Sun Aug 2 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/include/crypto/util.h \- utility functions for working with crypto  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_mbedtls_error\fP (int errcode)"
.br
.RI "prints the corresponding error to stdout "
.in -1c
.SH "Detailed Description"
.PP 
utility functions for working with crypto 


.PP
\fBAuthor\fP
.RS 4
bonedaddy 
.RE
.PP

.PP
Definition in file \fButil\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "void print_mbedtls_error (int errcode)"

.PP
prints the corresponding error to stdout 
.PP
Definition at line 7 of file util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
