.TH "/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/util.c" 3 "Wed Jul 22 2020" "libcp2p" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/media/solidity/DATA/Code/RTradeLtd/libcp2p/src/crypto/util.c
.SH SYNOPSIS
.br
.PP
\fC#include 'crypto/util\&.h'\fP
.br
\fC#include 'mbedtls/error\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_mbedtls_error\fP (int errcode)"
.br
.RI "prints the corresponding error to stdout "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void print_mbedtls_error (int errcode)"

.PP
prints the corresponding error to stdout 
.PP
Definition at line 7 of file util\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for libcp2p from the source code\&.
