var annotated_dup =
[
    [ "addrinfo", "d6/d9d/structaddrinfo.html", null ],
    [ "base", "d4/d87/structbase.html", null ],
    [ "bsem", "d5/d93/structbsem.html", "d5/d93/structbsem" ],
    [ "client_conn", "d5/de2/structclient__conn.html", "d5/de2/structclient__conn" ],
    [ "conn_handle_data", "de/da7/structconn__handle__data.html", "de/da7/structconn__handle__data" ],
    [ "file_logger", "d5/d99/structfile__logger.html", "d5/d99/structfile__logger" ],
    [ "job", "d3/d8c/structjob.html", "d3/d8c/structjob" ],
    [ "jobqueue", "d7/dd0/structjobqueue.html", "d7/dd0/structjobqueue" ],
    [ "map_base_t", "db/d57/structmap__base__t.html", "db/d57/structmap__base__t" ],
    [ "map_char_t", "d1/d1d/structmap__char__t.html", "d1/d1d/structmap__char__t" ],
    [ "map_double_t", "d9/d28/structmap__double__t.html", "d9/d28/structmap__double__t" ],
    [ "map_float_t", "d2/d15/structmap__float__t.html", "d2/d15/structmap__float__t" ],
    [ "map_int_t", "d5/db4/structmap__int__t.html", "d5/db4/structmap__int__t" ],
    [ "map_iter_t", "d8/d90/structmap__iter__t.html", "d8/d90/structmap__iter__t" ],
    [ "map_node_t", "d7/d1e/structmap__node__t.html", "d7/d1e/structmap__node__t" ],
    [ "map_str_t", "d1/d3e/structmap__str__t.html", "d1/d3e/structmap__str__t" ],
    [ "map_void_t", "da/d2c/structmap__void__t.html", "da/d2c/structmap__void__t" ],
    [ "sockaddr", "d5/dad/structsockaddr.html", null ],
    [ "sockaddr_storage", "d0/d6d/structsockaddr__storage.html", null ],
    [ "socket_client", "d9/d8c/structsocket__client.html", "d9/d8c/structsocket__client" ],
    [ "socket_server", "d7/d8d/structsocket__server.html", "d7/d8d/structsocket__server" ],
    [ "socket_server_config", "d9/d90/structsocket__server__config.html", "d9/d90/structsocket__server__config" ],
    [ "thpool_", "d4/d05/structthpool__.html", "d4/d05/structthpool__" ],
    [ "thread", "d3/dc5/structthread.html", "d3/dc5/structthread" ],
    [ "thread_logger", "da/da5/structthread__logger.html", "da/da5/structthread__logger" ],
    [ "timeval", "d1/d1b/structtimeval.html", null ]
];