var annotated_dup =
[
    [ "addrinfo", "d6/d9d/structaddrinfo.html", null ],
    [ "base", "d4/d87/structbase.html", null ],
    [ "base32_decode_context", "d3/d2c/structbase32__decode__context.html", "d3/d2c/structbase32__decode__context" ],
    [ "bsem", "d5/d93/structbsem.html", "d5/d93/structbsem" ],
    [ "Cid", "d5/d6c/struct_cid.html", "d5/d6c/struct_cid" ],
    [ "CidSet", "d8/d0e/struct_cid_set.html", "d8/d0e/struct_cid_set" ],
    [ "client_conn", "d5/de2/structclient__conn.html", "d5/de2/structclient__conn" ],
    [ "conn_handle_data", "de/da7/structconn__handle__data.html", "de/da7/structconn__handle__data" ],
    [ "ecdsa_private_key", "d7/dc6/structecdsa__private__key.html", "d7/dc6/structecdsa__private__key" ],
    [ "EphemeralPrivateKey", "d0/d5b/struct_ephemeral_private_key.html", "d0/d5b/struct_ephemeral_private_key" ],
    [ "EphemeralPublicKey", "d7/d04/struct_ephemeral_public_key.html", "d7/d04/struct_ephemeral_public_key" ],
    [ "file_logger", "d5/d99/structfile__logger.html", "d5/d99/structfile__logger" ],
    [ "hash_info", "d8/da0/structhash__info.html", "d8/da0/structhash__info" ],
    [ "job", "d3/d8c/structjob.html", "d3/d8c/structjob" ],
    [ "jobqueue", "d7/dd0/structjobqueue.html", "d7/dd0/structjobqueue" ],
    [ "multi_address", "d4/dc4/structmulti__address.html", "d4/dc4/structmulti__address" ],
    [ "multicodec_encoded", "d1/d8e/structmulticodec__encoded.html", "d1/d8e/structmulticodec__encoded" ],
    [ "PrivateKey", "d9/dc0/struct_private_key.html", "d9/dc0/struct_private_key" ],
    [ "Protocol", "d8/dde/struct_protocol.html", "d8/dde/struct_protocol" ],
    [ "ProtocolListItem", "d3/d6b/struct_protocol_list_item.html", "d3/d6b/struct_protocol_list_item" ],
    [ "PublicKey", "d5/dd7/struct_public_key.html", "d5/dd7/struct_public_key" ],
    [ "sockaddr", "d5/dad/structsockaddr.html", null ],
    [ "sockaddr_storage", "d0/d6d/structsockaddr__storage.html", null ],
    [ "socket_client", "d9/d8c/structsocket__client.html", "d9/d8c/structsocket__client" ],
    [ "socket_server", "d7/d8d/structsocket__server.html", "d7/d8d/structsocket__server" ],
    [ "socket_server_config", "d9/d90/structsocket__server__config.html", "d9/d90/structsocket__server__config" ],
    [ "StretchedKey", "dd/d9a/struct_stretched_key.html", "dd/d9a/struct_stretched_key" ],
    [ "Test1", "d0/dc5/struct_test1.html", "d0/dc5/struct_test1" ],
    [ "Test2", "d0/d2d/struct_test2.html", "d0/d2d/struct_test2" ],
    [ "Test3", "d7/dcc/struct_test3.html", "d7/dcc/struct_test3" ],
    [ "thpool_", "d4/d05/structthpool__.html", "d4/d05/structthpool__" ],
    [ "thread", "d3/dc5/structthread.html", "d3/dc5/structthread" ],
    [ "thread_logger", "da/da5/structthread__logger.html", "da/da5/structthread__logger" ],
    [ "timeval", "d1/d1b/structtimeval.html", null ]
];