add_executable(cli ${PROJECT_SOURCE_DIR}/src/cli/main.c ${PROJECT_SOURCE_DIR}/src/cli/command_line.c ${PROJECT_SOURCE_DIR}/include/cli/command_line.h)
target_compile_options(cli PRIVATE ${flags})
target_link_libraries(cli libutils)
target_link_libraries(cli argtable3)
target_link_libraries(cli m)